import { airtableWebhookTrigger } from '@/triggers/airtable'
import {
  ashbyApplicationSubmitTrigger,
  ashbyCandidateDeleteTrigger,
  ashbyCandidateHireTrigger,
  ashbyCandidateStageChangeTrigger,
  ashbyJobCreateTrigger,
  ashbyOfferCreateTrigger,
} from '@/triggers/ashby'
import {
  attioCommentCreatedTrigger,
  attioCommentDeletedTrigger,
  attioCommentResolvedTrigger,
  attioCommentUnresolvedTrigger,
  attioListCreatedTrigger,
  attioListDeletedTrigger,
  attioListEntryCreatedTrigger,
  attioListEntryDeletedTrigger,
  attioListEntryUpdatedTrigger,
  attioListUpdatedTrigger,
  attioNoteCreatedTrigger,
  attioNoteDeletedTrigger,
  attioNoteUpdatedTrigger,
  attioRecordCreatedTrigger,
  attioRecordDeletedTrigger,
  attioRecordMergedTrigger,
  attioRecordUpdatedTrigger,
  attioTaskCreatedTrigger,
  attioTaskDeletedTrigger,
  attioTaskUpdatedTrigger,
  attioWebhookTrigger,
  attioWorkspaceMemberCreatedTrigger,
} from '@/triggers/attio'
import {
  azureDevOpsBuildFailedTrigger,
  azureDevOpsWebhookTrigger,
  azureDevOpsWorkItemCreatedTrigger,
} from '@/triggers/azure_devops'
import {
  calcomBookingCancelledTrigger,
  calcomBookingCreatedTrigger,
  calcomBookingPaidTrigger,
  calcomBookingRejectedTrigger,
  calcomBookingRequestedTrigger,
  calcomBookingRescheduledTrigger,
  calcomMeetingEndedTrigger,
  calcomRecordingReadyTrigger,
  calcomWebhookTrigger,
} from '@/triggers/calcom'
import {
  calendlyInviteeCanceledTrigger,
  calendlyInviteeCreatedTrigger,
  calendlyRoutingFormSubmittedTrigger,
  calendlyWebhookTrigger,
} from '@/triggers/calendly'
import {
  circlebackMeetingCompletedTrigger,
  circlebackMeetingNotesTrigger,
  circlebackWebhookTrigger,
} from '@/triggers/circleback'
import {
  confluenceAttachmentCreatedTrigger,
  confluenceAttachmentRemovedTrigger,
  confluenceAttachmentUpdatedTrigger,
  confluenceBlogCreatedTrigger,
  confluenceBlogRemovedTrigger,
  confluenceBlogRestoredTrigger,
  confluenceBlogUpdatedTrigger,
  confluenceCommentCreatedTrigger,
  confluenceCommentRemovedTrigger,
  confluenceCommentUpdatedTrigger,
  confluenceLabelAddedTrigger,
  confluenceLabelRemovedTrigger,
  confluencePageCreatedTrigger,
  confluencePageMovedTrigger,
  confluencePagePermissionsUpdatedTrigger,
  confluencePageRemovedTrigger,
  confluencePageRestoredTrigger,
  confluencePageUpdatedTrigger,
  confluenceSpaceCreatedTrigger,
  confluenceSpaceRemovedTrigger,
  confluenceSpaceUpdatedTrigger,
  confluenceUserCreatedTrigger,
  confluenceWebhookTrigger,
} from '@/triggers/confluence'
import {
  emailBisonEmailAccountAddedTrigger,
  emailBisonEmailAccountDisconnectedTrigger,
  emailBisonEmailAccountReconnectedTrigger,
  emailBisonEmailAccountRemovedTrigger,
  emailBisonEmailBouncedTrigger,
  emailBisonEmailOpenedTrigger,
  emailBisonEmailSentTrigger,
  emailBisonLeadFirstContactedTrigger,
  emailBisonLeadInterestedTrigger,
  emailBisonLeadRepliedTrigger,
  emailBisonLeadUnsubscribedTrigger,
  emailBisonManualEmailSentTrigger,
  emailBisonTagAttachedTrigger,
  emailBisonTagRemovedTrigger,
  emailBisonUntrackedReplyReceivedTrigger,
  emailBisonWarmupDisabledCausingBouncesTrigger,
  emailBisonWarmupDisabledReceivingBouncesTrigger,
} from '@/triggers/emailbison'
import { fathomNewMeetingTrigger, fathomWebhookTrigger } from '@/triggers/fathom'
import { firefliesTranscriptionCompleteTrigger } from '@/triggers/fireflies'
import { genericWebhookTrigger } from '@/triggers/generic'
import {
  githubIssueClosedTrigger,
  githubIssueCommentTrigger,
  githubIssueOpenedTrigger,
  githubPRClosedTrigger,
  githubPRCommentTrigger,
  githubPRMergedTrigger,
  githubPROpenedTrigger,
  githubPRReviewedTrigger,
  githubPushTrigger,
  githubReleasePublishedTrigger,
  githubWebhookTrigger,
  githubWorkflowRunTrigger,
} from '@/triggers/github'
import {
  gitlabCommentTrigger,
  gitlabIssueTrigger,
  gitlabMergeRequestTrigger,
  gitlabPipelineTrigger,
  gitlabPushTrigger,
  gitlabWebhookTrigger,
} from '@/triggers/gitlab'
import { gmailPollingTrigger } from '@/triggers/gmail'
import { gongCallCompletedTrigger, gongWebhookTrigger } from '@/triggers/gong'
import { googleCalendarPollingTrigger } from '@/triggers/google-calendar'
import { googleDrivePollingTrigger } from '@/triggers/google-drive'
import { googleSheetsPollingTrigger } from '@/triggers/google-sheets'
import { googleFormsWebhookTrigger } from '@/triggers/googleforms'
import {
  grainHighlightCreatedTrigger,
  grainHighlightUpdatedTrigger,
  grainItemAddedTrigger,
  grainItemUpdatedTrigger,
  grainRecordingCreatedTrigger,
  grainRecordingUpdatedTrigger,
  grainStoryCreatedTrigger,
  grainWebhookTrigger,
} from '@/triggers/grain'
import {
  greenhouseCandidateHiredTrigger,
  greenhouseCandidateRejectedTrigger,
  greenhouseCandidateStageChangeTrigger,
  greenhouseJobCreatedTrigger,
  greenhouseJobUpdatedTrigger,
  greenhouseNewApplicationTrigger,
  greenhouseOfferCreatedTrigger,
  greenhouseWebhookTrigger,
} from '@/triggers/greenhouse'
import { hubspotPollingTrigger } from '@/triggers/hubspot'
import { imapPollingTrigger } from '@/triggers/imap'
import {
  instantlyAccountErrorTrigger,
  instantlyAutoReplyReceivedTrigger,
  instantlyCampaignCompletedTrigger,
  instantlyEmailBouncedTrigger,
  instantlyEmailOpenedTrigger,
  instantlyEmailSentTrigger,
  instantlyLeadClosedTrigger,
  instantlyLeadInterestedTrigger,
  instantlyLeadMeetingBookedTrigger,
  instantlyLeadMeetingCompletedTrigger,
  instantlyLeadNeutralTrigger,
  instantlyLeadNoShowTrigger,
  instantlyLeadNotInterestedTrigger,
  instantlyLeadOutOfOfficeTrigger,
  instantlyLeadUnsubscribedTrigger,
  instantlyLeadWrongPersonTrigger,
  instantlyLinkClickedTrigger,
  instantlyReplyReceivedTrigger,
  instantlySupersearchEnrichmentCompletedTrigger,
  instantlyWebhookTrigger,
} from '@/triggers/instantly'
import {
  intercomContactCreatedTrigger,
  intercomConversationClosedTrigger,
  intercomConversationCreatedTrigger,
  intercomConversationReplyTrigger,
  intercomUserCreatedTrigger,
  intercomWebhookTrigger,
} from '@/triggers/intercom'
import {
  jiraCommentDeletedTrigger,
  jiraCommentUpdatedTrigger,
  jiraIssueCommentedTrigger,
  jiraIssueCreatedTrigger,
  jiraIssueDeletedTrigger,
  jiraIssueUpdatedTrigger,
  jiraProjectCreatedTrigger,
  jiraSprintClosedTrigger,
  jiraSprintCreatedTrigger,
  jiraSprintStartedTrigger,
  jiraVersionReleasedTrigger,
  jiraWebhookTrigger,
  jiraWorklogCreatedTrigger,
  jiraWorklogDeletedTrigger,
  jiraWorklogUpdatedTrigger,
} from '@/triggers/jira'
import {
  jsmRequestCommentedTrigger,
  jsmRequestCreatedTrigger,
  jsmRequestResolvedTrigger,
  jsmRequestUpdatedTrigger,
  jsmWebhookTrigger,
} from '@/triggers/jsm'
import {
  lemlistEmailBouncedTrigger,
  lemlistEmailClickedTrigger,
  lemlistEmailOpenedTrigger,
  lemlistEmailRepliedTrigger,
  lemlistEmailSentTrigger,
  lemlistInterestedTrigger,
  lemlistLinkedInRepliedTrigger,
  lemlistNotInterestedTrigger,
  lemlistWebhookTrigger,
} from '@/triggers/lemlist'
import {
  linearCommentCreatedTrigger,
  linearCommentCreatedV2Trigger,
  linearCommentUpdatedTrigger,
  linearCommentUpdatedV2Trigger,
  linearCustomerRequestCreatedTrigger,
  linearCustomerRequestCreatedV2Trigger,
  linearCustomerRequestUpdatedTrigger,
  linearCustomerRequestUpdatedV2Trigger,
  linearCycleCreatedTrigger,
  linearCycleCreatedV2Trigger,
  linearCycleUpdatedTrigger,
  linearCycleUpdatedV2Trigger,
  linearIssueCreatedTrigger,
  linearIssueCreatedV2Trigger,
  linearIssueRemovedTrigger,
  linearIssueRemovedV2Trigger,
  linearIssueUpdatedTrigger,
  linearIssueUpdatedV2Trigger,
  linearLabelCreatedTrigger,
  linearLabelCreatedV2Trigger,
  linearLabelUpdatedTrigger,
  linearLabelUpdatedV2Trigger,
  linearProjectCreatedTrigger,
  linearProjectCreatedV2Trigger,
  linearProjectUpdateCreatedTrigger,
  linearProjectUpdateCreatedV2Trigger,
  linearProjectUpdatedTrigger,
  linearProjectUpdatedV2Trigger,
  linearWebhookTrigger,
  linearWebhookV2Trigger,
} from '@/triggers/linear'
import {
  microsoftTeamsChatSubscriptionTrigger,
  microsoftTeamsWebhookTrigger,
} from '@/triggers/microsoftteams'
import {
  mondayColumnChangedTrigger,
  mondayItemArchivedTrigger,
  mondayItemCreatedTrigger,
  mondayItemDeletedTrigger,
  mondayItemMovedTrigger,
  mondayItemNameChangedTrigger,
  mondayStatusChangedTrigger,
  mondaySubitemCreatedTrigger,
  mondayUpdateCreatedTrigger,
} from '@/triggers/monday'
import {
  notionCommentCreatedTrigger,
  notionDatabaseCreatedTrigger,
  notionDatabaseDeletedTrigger,
  notionDatabaseSchemaUpdatedTrigger,
  notionPageContentUpdatedTrigger,
  notionPageCreatedTrigger,
  notionPageDeletedTrigger,
  notionPagePropertiesUpdatedTrigger,
  notionWebhookTrigger,
} from '@/triggers/notion'
import { outlookPollingTrigger } from '@/triggers/outlook'
import {
  pagerdutyIncidentAcknowledgedTrigger,
  pagerdutyIncidentEscalatedTrigger,
  pagerdutyIncidentReassignedTrigger,
  pagerdutyIncidentResolvedTrigger,
  pagerdutyIncidentTriggeredTrigger,
  pagerdutyWebhookTrigger,
} from '@/triggers/pagerduty'
import {
  resendEmailBouncedTrigger,
  resendEmailClickedTrigger,
  resendEmailComplainedTrigger,
  resendEmailDeliveredTrigger,
  resendEmailFailedTrigger,
  resendEmailOpenedTrigger,
  resendEmailSentTrigger,
  resendWebhookTrigger,
} from '@/triggers/resend'
import { rssPollingTrigger } from '@/triggers/rss'
import {
  salesforceCaseStatusChangedTrigger,
  salesforceOpportunityStageChangedTrigger,
  salesforceRecordCreatedTrigger,
  salesforceRecordDeletedTrigger,
  salesforceRecordUpdatedTrigger,
  salesforceWebhookTrigger,
} from '@/triggers/salesforce'
import {
  sendblueMessageReceivedTrigger,
  sendblueMessageStatusUpdatedTrigger,
} from '@/triggers/sendblue'
import {
  servicenowChangeRequestCreatedTrigger,
  servicenowChangeRequestUpdatedTrigger,
  servicenowIncidentCreatedTrigger,
  servicenowIncidentUpdatedTrigger,
  servicenowWebhookTrigger,
} from '@/triggers/servicenow'
import { simWorkspaceEventTrigger } from '@/triggers/sim'
import { slackWebhookTrigger } from '@/triggers/slack'
import { stripeWebhookTrigger } from '@/triggers/stripe'
import { tableNewRowTrigger } from '@/triggers/table'
import { telegramWebhookTrigger } from '@/triggers/telegram'
import { twilioVoiceWebhookTrigger } from '@/triggers/twilio_voice'
import { typeformWebhookTrigger } from '@/triggers/typeform'
import type { TriggerRegistry } from '@/triggers/types'
import {
  vercelDeploymentCanceledTrigger,
  vercelDeploymentCreatedTrigger,
  vercelDeploymentErrorTrigger,
  vercelDeploymentReadyTrigger,
  vercelDomainCreatedTrigger,
  vercelProjectCreatedTrigger,
  vercelProjectRemovedTrigger,
  vercelWebhookTrigger,
} from '@/triggers/vercel'
import {
  webflowCollectionItemChangedTrigger,
  webflowCollectionItemCreatedTrigger,
  webflowCollectionItemDeletedTrigger,
  webflowFormSubmissionTrigger,
} from '@/triggers/webflow'
import { whatsappWebhookTrigger } from '@/triggers/whatsapp'
import {
  zendeskTicketCommentAddedTrigger,
  zendeskTicketCreatedTrigger,
  zendeskTicketPriorityChangedTrigger,
  zendeskTicketStatusChangedTrigger,
  zendeskWebhookTrigger,
} from '@/triggers/zendesk'
import {
  zoomMeetingEndedTrigger,
  zoomMeetingStartedTrigger,
  zoomParticipantJoinedTrigger,
  zoomParticipantLeftTrigger,
  zoomRecordingCompletedTrigger,
  zoomWebhookTrigger,
} from '@/triggers/zoom'

export const TRIGGER_REGISTRY: TriggerRegistry = {
  slack_webhook: slackWebhookTrigger,
  airtable_webhook: airtableWebhookTrigger,
  ashby_application_submit: ashbyApplicationSubmitTrigger,
  ashby_candidate_stage_change: ashbyCandidateStageChangeTrigger,
  ashby_candidate_hire: ashbyCandidateHireTrigger,
  ashby_candidate_delete: ashbyCandidateDeleteTrigger,
  ashby_job_create: ashbyJobCreateTrigger,
  ashby_offer_create: ashbyOfferCreateTrigger,
  azure_devops_build_failed: azureDevOpsBuildFailedTrigger,
  azure_devops_webhook: azureDevOpsWebhookTrigger,
  azure_devops_work_item_created: azureDevOpsWorkItemCreatedTrigger,
  attio_webhook: attioWebhookTrigger,
  attio_record_created: attioRecordCreatedTrigger,
  attio_record_updated: attioRecordUpdatedTrigger,
  attio_record_deleted: attioRecordDeletedTrigger,
  attio_record_merged: attioRecordMergedTrigger,
  attio_note_created: attioNoteCreatedTrigger,
  attio_note_updated: attioNoteUpdatedTrigger,
  attio_note_deleted: attioNoteDeletedTrigger,
  attio_task_created: attioTaskCreatedTrigger,
  attio_task_updated: attioTaskUpdatedTrigger,
  attio_task_deleted: attioTaskDeletedTrigger,
  attio_comment_created: attioCommentCreatedTrigger,
  attio_comment_resolved: attioCommentResolvedTrigger,
  attio_comment_unresolved: attioCommentUnresolvedTrigger,
  attio_comment_deleted: attioCommentDeletedTrigger,
  attio_list_entry_created: attioListEntryCreatedTrigger,
  attio_list_entry_updated: attioListEntryUpdatedTrigger,
  attio_list_entry_deleted: attioListEntryDeletedTrigger,
  attio_list_created: attioListCreatedTrigger,
  attio_list_updated: attioListUpdatedTrigger,
  attio_list_deleted: attioListDeletedTrigger,
  attio_workspace_member_created: attioWorkspaceMemberCreatedTrigger,
  calendly_webhook: calendlyWebhookTrigger,
  calendly_invitee_created: calendlyInviteeCreatedTrigger,
  calendly_invitee_canceled: calendlyInviteeCanceledTrigger,
  calendly_routing_form_submitted: calendlyRoutingFormSubmittedTrigger,
  calcom_booking_created: calcomBookingCreatedTrigger,
  calcom_booking_cancelled: calcomBookingCancelledTrigger,
  calcom_booking_rescheduled: calcomBookingRescheduledTrigger,
  calcom_booking_requested: calcomBookingRequestedTrigger,
  calcom_booking_rejected: calcomBookingRejectedTrigger,
  calcom_booking_paid: calcomBookingPaidTrigger,
  calcom_meeting_ended: calcomMeetingEndedTrigger,
  calcom_recording_ready: calcomRecordingReadyTrigger,
  calcom_webhook: calcomWebhookTrigger,
  confluence_webhook: confluenceWebhookTrigger,
  confluence_page_created: confluencePageCreatedTrigger,
  confluence_page_updated: confluencePageUpdatedTrigger,
  confluence_page_removed: confluencePageRemovedTrigger,
  confluence_page_moved: confluencePageMovedTrigger,
  confluence_comment_created: confluenceCommentCreatedTrigger,
  confluence_comment_removed: confluenceCommentRemovedTrigger,
  confluence_blog_created: confluenceBlogCreatedTrigger,
  confluence_blog_updated: confluenceBlogUpdatedTrigger,
  confluence_blog_removed: confluenceBlogRemovedTrigger,
  confluence_attachment_created: confluenceAttachmentCreatedTrigger,
  confluence_attachment_removed: confluenceAttachmentRemovedTrigger,
  confluence_space_created: confluenceSpaceCreatedTrigger,
  confluence_space_updated: confluenceSpaceUpdatedTrigger,
  confluence_label_added: confluenceLabelAddedTrigger,
  confluence_label_removed: confluenceLabelRemovedTrigger,
  confluence_comment_updated: confluenceCommentUpdatedTrigger,
  confluence_attachment_updated: confluenceAttachmentUpdatedTrigger,
  confluence_page_restored: confluencePageRestoredTrigger,
  confluence_blog_restored: confluenceBlogRestoredTrigger,
  confluence_space_removed: confluenceSpaceRemovedTrigger,
  confluence_page_permissions_updated: confluencePagePermissionsUpdatedTrigger,
  confluence_user_created: confluenceUserCreatedTrigger,
  emailbison_email_sent: emailBisonEmailSentTrigger,
  emailbison_lead_first_contacted: emailBisonLeadFirstContactedTrigger,
  emailbison_lead_replied: emailBisonLeadRepliedTrigger,
  emailbison_lead_interested: emailBisonLeadInterestedTrigger,
  emailbison_lead_unsubscribed: emailBisonLeadUnsubscribedTrigger,
  emailbison_untracked_reply_received: emailBisonUntrackedReplyReceivedTrigger,
  emailbison_email_opened: emailBisonEmailOpenedTrigger,
  emailbison_email_bounced: emailBisonEmailBouncedTrigger,
  emailbison_email_account_added: emailBisonEmailAccountAddedTrigger,
  emailbison_email_account_removed: emailBisonEmailAccountRemovedTrigger,
  emailbison_email_account_disconnected: emailBisonEmailAccountDisconnectedTrigger,
  emailbison_email_account_reconnected: emailBisonEmailAccountReconnectedTrigger,
  emailbison_manual_email_sent: emailBisonManualEmailSentTrigger,
  emailbison_tag_attached: emailBisonTagAttachedTrigger,
  emailbison_tag_removed: emailBisonTagRemovedTrigger,
  emailbison_warmup_disabled_receiving_bounces: emailBisonWarmupDisabledReceivingBouncesTrigger,
  emailbison_warmup_disabled_causing_bounces: emailBisonWarmupDisabledCausingBouncesTrigger,
  generic_webhook: genericWebhookTrigger,
  greenhouse_candidate_hired: greenhouseCandidateHiredTrigger,
  greenhouse_new_application: greenhouseNewApplicationTrigger,
  greenhouse_candidate_stage_change: greenhouseCandidateStageChangeTrigger,
  greenhouse_candidate_rejected: greenhouseCandidateRejectedTrigger,
  greenhouse_offer_created: greenhouseOfferCreatedTrigger,
  greenhouse_job_created: greenhouseJobCreatedTrigger,
  greenhouse_job_updated: greenhouseJobUpdatedTrigger,
  greenhouse_webhook: greenhouseWebhookTrigger,
  github_webhook: githubWebhookTrigger,
  github_issue_opened: githubIssueOpenedTrigger,
  github_issue_closed: githubIssueClosedTrigger,
  github_issue_comment: githubIssueCommentTrigger,
  github_pr_opened: githubPROpenedTrigger,
  github_pr_closed: githubPRClosedTrigger,
  github_pr_merged: githubPRMergedTrigger,
  github_pr_comment: githubPRCommentTrigger,
  github_pr_reviewed: githubPRReviewedTrigger,
  github_push: githubPushTrigger,
  github_release_published: githubReleasePublishedTrigger,
  github_workflow_run: githubWorkflowRunTrigger,
  gitlab_push: gitlabPushTrigger,
  gitlab_merge_request: gitlabMergeRequestTrigger,
  gitlab_issue: gitlabIssueTrigger,
  gitlab_pipeline: gitlabPipelineTrigger,
  gitlab_comment: gitlabCommentTrigger,
  gitlab_webhook: gitlabWebhookTrigger,
  fireflies_transcription_complete: firefliesTranscriptionCompleteTrigger,
  fathom_new_meeting: fathomNewMeetingTrigger,
  fathom_webhook: fathomWebhookTrigger,
  gmail_poller: gmailPollingTrigger,
  google_calendar_poller: googleCalendarPollingTrigger,
  google_drive_poller: googleDrivePollingTrigger,
  google_sheets_poller: googleSheetsPollingTrigger,
  gong_call_completed: gongCallCompletedTrigger,
  gong_webhook: gongWebhookTrigger,
  grain_webhook: grainWebhookTrigger,
  grain_item_added: grainItemAddedTrigger,
  grain_item_updated: grainItemUpdatedTrigger,
  grain_recording_created: grainRecordingCreatedTrigger,
  grain_recording_updated: grainRecordingUpdatedTrigger,
  grain_highlight_created: grainHighlightCreatedTrigger,
  grain_highlight_updated: grainHighlightUpdatedTrigger,
  grain_story_created: grainStoryCreatedTrigger,
  circleback_meeting_completed: circlebackMeetingCompletedTrigger,
  circleback_meeting_notes: circlebackMeetingNotesTrigger,
  circleback_webhook: circlebackWebhookTrigger,
  jira_webhook: jiraWebhookTrigger,
  jira_issue_created: jiraIssueCreatedTrigger,
  jira_issue_updated: jiraIssueUpdatedTrigger,
  jira_issue_deleted: jiraIssueDeletedTrigger,
  jira_issue_commented: jiraIssueCommentedTrigger,
  jira_comment_updated: jiraCommentUpdatedTrigger,
  jira_comment_deleted: jiraCommentDeletedTrigger,
  jira_worklog_created: jiraWorklogCreatedTrigger,
  jira_worklog_updated: jiraWorklogUpdatedTrigger,
  jira_worklog_deleted: jiraWorklogDeletedTrigger,
  jira_sprint_created: jiraSprintCreatedTrigger,
  jira_sprint_started: jiraSprintStartedTrigger,
  jira_sprint_closed: jiraSprintClosedTrigger,
  jira_project_created: jiraProjectCreatedTrigger,
  jira_version_released: jiraVersionReleasedTrigger,
  jsm_request_created: jsmRequestCreatedTrigger,
  jsm_request_updated: jsmRequestUpdatedTrigger,
  jsm_request_commented: jsmRequestCommentedTrigger,
  jsm_request_resolved: jsmRequestResolvedTrigger,
  jsm_webhook: jsmWebhookTrigger,
  lemlist_webhook: lemlistWebhookTrigger,
  lemlist_email_replied: lemlistEmailRepliedTrigger,
  lemlist_email_opened: lemlistEmailOpenedTrigger,
  lemlist_email_clicked: lemlistEmailClickedTrigger,
  lemlist_email_sent: lemlistEmailSentTrigger,
  lemlist_email_bounced: lemlistEmailBouncedTrigger,
  lemlist_linkedin_replied: lemlistLinkedInRepliedTrigger,
  lemlist_interested: lemlistInterestedTrigger,
  lemlist_not_interested: lemlistNotInterestedTrigger,
  linear_webhook: linearWebhookTrigger,
  linear_issue_created: linearIssueCreatedTrigger,
  linear_issue_updated: linearIssueUpdatedTrigger,
  linear_issue_removed: linearIssueRemovedTrigger,
  linear_comment_created: linearCommentCreatedTrigger,
  linear_comment_updated: linearCommentUpdatedTrigger,
  linear_project_created: linearProjectCreatedTrigger,
  linear_project_updated: linearProjectUpdatedTrigger,
  linear_cycle_created: linearCycleCreatedTrigger,
  linear_cycle_updated: linearCycleUpdatedTrigger,
  linear_label_created: linearLabelCreatedTrigger,
  linear_label_updated: linearLabelUpdatedTrigger,
  linear_project_update_created: linearProjectUpdateCreatedTrigger,
  linear_customer_request_created: linearCustomerRequestCreatedTrigger,
  linear_customer_request_updated: linearCustomerRequestUpdatedTrigger,
  linear_webhook_v2: linearWebhookV2Trigger,
  linear_issue_created_v2: linearIssueCreatedV2Trigger,
  linear_issue_updated_v2: linearIssueUpdatedV2Trigger,
  linear_issue_removed_v2: linearIssueRemovedV2Trigger,
  linear_comment_created_v2: linearCommentCreatedV2Trigger,
  linear_comment_updated_v2: linearCommentUpdatedV2Trigger,
  linear_project_created_v2: linearProjectCreatedV2Trigger,
  linear_project_updated_v2: linearProjectUpdatedV2Trigger,
  linear_cycle_created_v2: linearCycleCreatedV2Trigger,
  linear_cycle_updated_v2: linearCycleUpdatedV2Trigger,
  linear_label_created_v2: linearLabelCreatedV2Trigger,
  linear_label_updated_v2: linearLabelUpdatedV2Trigger,
  linear_project_update_created_v2: linearProjectUpdateCreatedV2Trigger,
  linear_customer_request_created_v2: linearCustomerRequestCreatedV2Trigger,
  linear_customer_request_updated_v2: linearCustomerRequestUpdatedV2Trigger,
  monday_item_created: mondayItemCreatedTrigger,
  monday_column_changed: mondayColumnChangedTrigger,
  monday_status_changed: mondayStatusChangedTrigger,
  monday_item_name_changed: mondayItemNameChangedTrigger,
  monday_item_archived: mondayItemArchivedTrigger,
  monday_item_deleted: mondayItemDeletedTrigger,
  monday_item_moved: mondayItemMovedTrigger,
  monday_subitem_created: mondaySubitemCreatedTrigger,
  monday_update_created: mondayUpdateCreatedTrigger,
  microsoftteams_webhook: microsoftTeamsWebhookTrigger,
  microsoftteams_chat_subscription: microsoftTeamsChatSubscriptionTrigger,
  notion_page_created: notionPageCreatedTrigger,
  notion_page_properties_updated: notionPagePropertiesUpdatedTrigger,
  notion_page_content_updated: notionPageContentUpdatedTrigger,
  notion_page_deleted: notionPageDeletedTrigger,
  notion_database_created: notionDatabaseCreatedTrigger,
  notion_database_schema_updated: notionDatabaseSchemaUpdatedTrigger,
  notion_database_deleted: notionDatabaseDeletedTrigger,
  notion_comment_created: notionCommentCreatedTrigger,
  notion_webhook: notionWebhookTrigger,
  outlook_poller: outlookPollingTrigger,
  pagerduty_incident_triggered: pagerdutyIncidentTriggeredTrigger,
  pagerduty_incident_acknowledged: pagerdutyIncidentAcknowledgedTrigger,
  pagerduty_incident_resolved: pagerdutyIncidentResolvedTrigger,
  pagerduty_incident_escalated: pagerdutyIncidentEscalatedTrigger,
  pagerduty_incident_reassigned: pagerdutyIncidentReassignedTrigger,
  pagerduty_webhook: pagerdutyWebhookTrigger,
  resend_email_sent: resendEmailSentTrigger,
  resend_email_delivered: resendEmailDeliveredTrigger,
  resend_email_bounced: resendEmailBouncedTrigger,
  resend_email_complained: resendEmailComplainedTrigger,
  resend_email_opened: resendEmailOpenedTrigger,
  resend_email_clicked: resendEmailClickedTrigger,
  resend_email_failed: resendEmailFailedTrigger,
  resend_webhook: resendWebhookTrigger,
  rss_poller: rssPollingTrigger,
  salesforce_record_created: salesforceRecordCreatedTrigger,
  salesforce_record_updated: salesforceRecordUpdatedTrigger,
  salesforce_record_deleted: salesforceRecordDeletedTrigger,
  salesforce_opportunity_stage_changed: salesforceOpportunityStageChangedTrigger,
  salesforce_case_status_changed: salesforceCaseStatusChangedTrigger,
  salesforce_webhook: salesforceWebhookTrigger,
  sendblue_message_received: sendblueMessageReceivedTrigger,
  sendblue_message_status_updated: sendblueMessageStatusUpdatedTrigger,
  servicenow_incident_created: servicenowIncidentCreatedTrigger,
  servicenow_incident_updated: servicenowIncidentUpdatedTrigger,
  servicenow_change_request_created: servicenowChangeRequestCreatedTrigger,
  servicenow_change_request_updated: servicenowChangeRequestUpdatedTrigger,
  servicenow_webhook: servicenowWebhookTrigger,
  sim_workspace_event: simWorkspaceEventTrigger,
  stripe_webhook: stripeWebhookTrigger,
  table_new_row: tableNewRowTrigger,
  telegram_webhook: telegramWebhookTrigger,
  typeform_webhook: typeformWebhookTrigger,
  whatsapp_webhook: whatsappWebhookTrigger,
  google_forms_webhook: googleFormsWebhookTrigger,
  twilio_voice_webhook: twilioVoiceWebhookTrigger,
  vercel_deployment_created: vercelDeploymentCreatedTrigger,
  vercel_deployment_ready: vercelDeploymentReadyTrigger,
  vercel_deployment_error: vercelDeploymentErrorTrigger,
  vercel_deployment_canceled: vercelDeploymentCanceledTrigger,
  vercel_project_created: vercelProjectCreatedTrigger,
  vercel_project_removed: vercelProjectRemovedTrigger,
  vercel_domain_created: vercelDomainCreatedTrigger,
  vercel_webhook: vercelWebhookTrigger,
  webflow_collection_item_created: webflowCollectionItemCreatedTrigger,
  webflow_collection_item_changed: webflowCollectionItemChangedTrigger,
  webflow_collection_item_deleted: webflowCollectionItemDeletedTrigger,
  webflow_form_submission: webflowFormSubmissionTrigger,
  hubspot_poller: hubspotPollingTrigger,
  imap_poller: imapPollingTrigger,
  intercom_conversation_created: intercomConversationCreatedTrigger,
  intercom_conversation_reply: intercomConversationReplyTrigger,
  intercom_conversation_closed: intercomConversationClosedTrigger,
  intercom_contact_created: intercomContactCreatedTrigger,
  intercom_user_created: intercomUserCreatedTrigger,
  intercom_webhook: intercomWebhookTrigger,
  instantly_webhook: instantlyWebhookTrigger,
  instantly_email_sent: instantlyEmailSentTrigger,
  instantly_email_opened: instantlyEmailOpenedTrigger,
  instantly_reply_received: instantlyReplyReceivedTrigger,
  instantly_auto_reply_received: instantlyAutoReplyReceivedTrigger,
  instantly_link_clicked: instantlyLinkClickedTrigger,
  instantly_email_bounced: instantlyEmailBouncedTrigger,
  instantly_lead_unsubscribed: instantlyLeadUnsubscribedTrigger,
  instantly_account_error: instantlyAccountErrorTrigger,
  instantly_campaign_completed: instantlyCampaignCompletedTrigger,
  instantly_lead_neutral: instantlyLeadNeutralTrigger,
  instantly_lead_interested: instantlyLeadInterestedTrigger,
  instantly_lead_not_interested: instantlyLeadNotInterestedTrigger,
  instantly_lead_meeting_booked: instantlyLeadMeetingBookedTrigger,
  instantly_lead_meeting_completed: instantlyLeadMeetingCompletedTrigger,
  instantly_lead_closed: instantlyLeadClosedTrigger,
  instantly_lead_out_of_office: instantlyLeadOutOfOfficeTrigger,
  instantly_lead_wrong_person: instantlyLeadWrongPersonTrigger,
  instantly_lead_no_show: instantlyLeadNoShowTrigger,
  instantly_supersearch_enrichment_completed: instantlySupersearchEnrichmentCompletedTrigger,
  zoom_meeting_started: zoomMeetingStartedTrigger,
  zendesk_ticket_created: zendeskTicketCreatedTrigger,
  zendesk_ticket_status_changed: zendeskTicketStatusChangedTrigger,
  zendesk_ticket_comment_added: zendeskTicketCommentAddedTrigger,
  zendesk_ticket_priority_changed: zendeskTicketPriorityChangedTrigger,
  zendesk_webhook: zendeskWebhookTrigger,
  zoom_meeting_ended: zoomMeetingEndedTrigger,
  zoom_participant_joined: zoomParticipantJoinedTrigger,
  zoom_participant_left: zoomParticipantLeftTrigger,
  zoom_recording_completed: zoomRecordingCompletedTrigger,
  zoom_webhook: zoomWebhookTrigger,
}
