-- Generated by drizzle-kit, then converted to CONCURRENTLY per scripts/migrate.ts (plain
-- CREATE/DROP INDEX takes ACCESS EXCLUSIVE for the whole op, write-locking the table).
--
-- ADD workflow_execution_logs (workspace_id, started_at DESC NULLS LAST, id DESC): serves the
-- logs-list query (lib/logs/list-logs.ts, app/api/v1/logs, app/api/logs/export) ordered by
-- started_at DESC with an id tiebreaker as an index-only scan that early-exits under LIMIT,
-- replacing an in-memory sort over the matched rows. The existing
-- workflow_execution_logs_workspace_started_at_idx is intentionally KEPT — it still serves the
-- ascending/range log queries that this DESC index does not cover.
--
-- DROP three redundant indexes, each a left-prefix of an existing superset (equality-prefix only,
-- no ordering subtlety; no query, foreign key, or constraint depends on the narrow index):
--   permission_group_workspace_group_id_idx  ⊂ permission_group_workspace_group_workspace_unique
--   user_table_rows_table_id_idx             ⊂ user_table_rows_table_order_key_idx (+ others)
--   workspace_byok_workspace_idx             ⊂ workspace_byok_workspace_provider_idx
--
-- The embedded COMMIT drops out of drizzle's batch transaction; everything below runs in
-- autocommit (CONCURRENTLY cannot run in a transaction) and is idempotent for safe replay.
COMMIT;--> statement-breakpoint
SET lock_timeout = 0;--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workflow_execution_logs_workspace_started_at_id_desc_idx" ON "workflow_execution_logs" USING btree ("workspace_id","started_at" DESC NULLS LAST,"id" DESC);--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "permission_group_workspace_group_id_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "user_table_rows_table_id_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "workspace_byok_workspace_idx";--> statement-breakpoint
SET lock_timeout = '5s';
