import { SportmonksIcon } from '@/components/icons'
import { AuthMode, type BlockConfig, type BlockMeta, IntegrationType } from '@/blocks/types'

const DATE_WAND_CONFIG = {
  enabled: true,
  prompt: `Generate a calendar date in YYYY-MM-DD format based on the user's description.
Examples:
- "today" -> today's date in YYYY-MM-DD
- "this weekend" -> the date of the upcoming Sunday in YYYY-MM-DD

Return ONLY the date string in YYYY-MM-DD format - no explanations, no quotes, no extra text.`,
  placeholder: 'Describe the date (e.g., "today", "this weekend")...',
  generationType: 'timestamp' as const,
}

const INCLUDE_OPS = [
  'football_get_team',
  'football_get_totw',
  'core_get_cities',
  'core_get_city',
  'core_get_continent',
  'core_get_continents',
  'core_get_countries',
  'core_get_country',
  'core_get_region',
  'core_get_regions',
  'core_search_cities',
  'core_search_countries',
  'core_search_regions',
  'football_expected_by_player',
  'football_expected_by_team',
  'football_get_all_commentaries',
  'football_get_all_fixtures',
  'football_get_all_players',
  'football_get_all_rivals',
  'football_get_all_teams',
  'football_get_all_transfer_rumours',
  'football_get_all_transfers',
  'football_get_brackets_by_season',
  'football_get_coach',
  'football_get_coaches',
  'football_get_coaches_by_country',
  'football_get_commentaries_by_fixture',
  'football_get_current_leagues_by_team',
  'football_get_expected_lineups_by_player',
  'football_get_expected_lineups_by_team',
  'football_get_extended_team_squad',
  'football_get_fixture',
  'football_get_fixtures_by_date',
  'football_get_fixtures_by_date_range',
  'football_get_fixtures_by_date_range_for_team',
  'football_get_fixtures_by_ids',
  'football_get_grouped_standings_by_round',
  'football_get_head_to_head',
  'football_get_inplay_livescores',
  'football_get_latest_coaches',
  'football_get_latest_fixtures',
  'football_get_latest_livescores',
  'football_get_latest_players',
  'football_get_latest_totw',
  'football_get_latest_transfers',
  'football_get_league',
  'football_get_leagues',
  'football_get_leagues_by_country',
  'football_get_leagues_by_date',
  'football_get_leagues_by_team',
  'football_get_live_leagues',
  'football_get_live_probabilities',
  'football_get_live_probabilities_by_fixture',
  'football_get_live_standings_by_league',
  'football_get_livescores',
  'football_get_match_facts',
  'football_get_match_facts_by_date_range',
  'football_get_match_facts_by_fixture',
  'football_get_match_facts_by_league',
  'football_get_past_fixtures_by_tv_station',
  'football_get_player',
  'football_get_players_by_country',
  'football_get_postmatch_news',
  'football_get_postmatch_news_by_season',
  'football_get_predictability_by_league',
  'football_get_prematch_news',
  'football_get_prematch_news_by_season',
  'football_get_prematch_news_upcoming',
  'football_get_probabilities',
  'football_get_probabilities_by_fixture',
  'football_get_referee',
  'football_get_referees',
  'football_get_referees_by_country',
  'football_get_referees_by_season',
  'football_get_rivals_by_team',
  'football_get_round',
  'football_get_round_statistics',
  'football_get_rounds',
  'football_get_rounds_by_season',
  'football_get_season',
  'football_get_seasons',
  'football_get_seasons_by_team',
  'football_get_stage',
  'football_get_stage_statistics',
  'football_get_stages',
  'football_get_stages_by_season',
  'football_get_standing_corrections_by_season',
  'football_get_standings',
  'football_get_standings_by_round',
  'football_get_standings_by_season',
  'football_get_team_rankings',
  'football_get_team_rankings_by_date',
  'football_get_team_rankings_by_team',
  'football_get_team_squad',
  'football_get_team_squad_by_season',
  'football_get_teams_by_country',
  'football_get_teams_by_season',
  'football_get_topscorers_by_season',
  'football_get_topscorers_by_stage',
  'football_get_totw_by_round',
  'football_get_transfer',
  'football_get_transfer_rumour',
  'football_get_transfer_rumours_between_dates',
  'football_get_transfer_rumours_by_player',
  'football_get_transfer_rumours_by_team',
  'football_get_transfers_between_dates',
  'football_get_transfers_by_player',
  'football_get_transfers_by_team',
  'football_get_tv_station',
  'football_get_tv_stations',
  'football_get_tv_stations_by_fixture',
  'football_get_upcoming_fixtures_by_market',
  'football_get_upcoming_fixtures_by_tv_station',
  'football_get_value_bets',
  'football_get_value_bets_by_fixture',
  'football_get_venue',
  'football_get_venues',
  'football_get_venues_by_season',
  'football_search_coaches',
  'football_search_fixtures',
  'football_search_leagues',
  'football_search_players',
  'football_search_referees',
  'football_search_rounds',
  'football_search_seasons',
  'football_search_stages',
  'football_search_teams',
  'football_search_venues',
  'motorsport_get_all_fixtures',
  'motorsport_get_current_leagues_by_team',
  'motorsport_get_driver',
  'motorsport_get_driver_standings',
  'motorsport_get_driver_standings_by_season',
  'motorsport_get_drivers',
  'motorsport_get_drivers_by_country',
  'motorsport_get_drivers_by_season',
  'motorsport_get_fixture',
  'motorsport_get_fixtures_by_date',
  'motorsport_get_fixtures_by_date_range',
  'motorsport_get_fixtures_by_ids',
  'motorsport_get_laps_by_fixture',
  'motorsport_get_laps_by_fixture_and_driver',
  'motorsport_get_laps_by_fixture_and_lap',
  'motorsport_get_latest_laps_by_fixture',
  'motorsport_get_latest_pitstops_by_fixture',
  'motorsport_get_latest_stints_by_fixture',
  'motorsport_get_latest_updated_drivers',
  'motorsport_get_latest_updated_fixtures',
  'motorsport_get_league',
  'motorsport_get_leagues',
  'motorsport_get_leagues_by_country',
  'motorsport_get_leagues_by_date',
  'motorsport_get_leagues_by_live',
  'motorsport_get_leagues_by_team',
  'motorsport_get_livescores',
  'motorsport_get_pitstops_by_fixture',
  'motorsport_get_pitstops_by_fixture_and_driver',
  'motorsport_get_pitstops_by_fixture_and_lap',
  'motorsport_get_race_results_by_season_and_driver',
  'motorsport_get_race_results_by_season_and_team',
  'motorsport_get_schedules_by_season',
  'motorsport_get_season',
  'motorsport_get_seasons',
  'motorsport_get_stage',
  'motorsport_get_stages',
  'motorsport_get_stages_by_season',
  'motorsport_get_state',
  'motorsport_get_states',
  'motorsport_get_stints_by_fixture',
  'motorsport_get_stints_by_fixture_and_driver',
  'motorsport_get_stints_by_fixture_and_stint',
  'motorsport_get_team',
  'motorsport_get_team_standings',
  'motorsport_get_team_standings_by_season',
  'motorsport_get_teams',
  'motorsport_get_teams_by_country',
  'motorsport_get_teams_by_season',
  'motorsport_get_venue',
  'motorsport_get_venues',
  'motorsport_get_venues_by_season',
  'motorsport_search_drivers',
  'motorsport_search_leagues',
  'motorsport_search_stages',
  'motorsport_search_teams',
  'motorsport_search_venues',
  'odds_get_all_historical_odds',
  'odds_get_all_inplay_odds',
  'odds_get_all_pre_match_odds',
  'odds_get_all_premium_odds',
  'odds_get_inplay_odds_by_fixture',
  'odds_get_inplay_odds_by_fixture_and_bookmaker',
  'odds_get_inplay_odds_by_fixture_and_market',
  'odds_get_last_updated_inplay_odds',
  'odds_get_last_updated_pre_match_odds',
  'odds_get_pre_match_odds_by_fixture',
  'odds_get_pre_match_odds_by_fixture_and_bookmaker',
  'odds_get_pre_match_odds_by_fixture_and_market',
  'odds_get_premium_odds_by_fixture',
  'odds_get_premium_odds_by_fixture_and_bookmaker',
  'odds_get_premium_odds_by_fixture_and_market',
  'odds_get_updated_historical_odds_between',
  'odds_get_updated_premium_odds_between',
]

const FILTER_OPS = [
  'football_get_team',
  'core_get_cities',
  'core_get_countries',
  'core_get_regions',
  'core_search_cities',
  'core_search_countries',
  'core_search_regions',
  'football_expected_by_player',
  'football_expected_by_team',
  'football_get_all_commentaries',
  'football_get_all_fixtures',
  'football_get_all_players',
  'football_get_all_rivals',
  'football_get_all_teams',
  'football_get_all_transfer_rumours',
  'football_get_all_transfers',
  'football_get_coach',
  'football_get_coaches',
  'football_get_coaches_by_country',
  'football_get_current_leagues_by_team',
  'football_get_expected_lineups_by_player',
  'football_get_expected_lineups_by_team',
  'football_get_extended_team_squad',
  'football_get_fixture',
  'football_get_fixtures_by_date',
  'football_get_fixtures_by_date_range',
  'football_get_fixtures_by_date_range_for_team',
  'football_get_fixtures_by_ids',
  'football_get_grouped_standings_by_round',
  'football_get_head_to_head',
  'football_get_inplay_livescores',
  'football_get_latest_coaches',
  'football_get_latest_fixtures',
  'football_get_latest_livescores',
  'football_get_latest_players',
  'football_get_latest_transfers',
  'football_get_league',
  'football_get_leagues',
  'football_get_leagues_by_country',
  'football_get_leagues_by_date',
  'football_get_leagues_by_team',
  'football_get_live_leagues',
  'football_get_live_standings_by_league',
  'football_get_livescores',
  'football_get_match_facts',
  'football_get_match_facts_by_date_range',
  'football_get_match_facts_by_fixture',
  'football_get_match_facts_by_league',
  'football_get_past_fixtures_by_tv_station',
  'football_get_player',
  'football_get_players_by_country',
  'football_get_postmatch_news',
  'football_get_postmatch_news_by_season',
  'football_get_predictability_by_league',
  'football_get_prematch_news',
  'football_get_prematch_news_by_season',
  'football_get_prematch_news_upcoming',
  'football_get_probabilities',
  'football_get_probabilities_by_fixture',
  'football_get_referee',
  'football_get_referees',
  'football_get_referees_by_country',
  'football_get_referees_by_season',
  'football_get_round',
  'football_get_round_statistics',
  'football_get_rounds',
  'football_get_rounds_by_season',
  'football_get_season',
  'football_get_seasons',
  'football_get_seasons_by_team',
  'football_get_stage',
  'football_get_stage_statistics',
  'football_get_stages',
  'football_get_stages_by_season',
  'football_get_standing_corrections_by_season',
  'football_get_standings',
  'football_get_standings_by_round',
  'football_get_standings_by_season',
  'football_get_team_squad',
  'football_get_team_squad_by_season',
  'football_get_teams_by_country',
  'football_get_teams_by_season',
  'football_get_topscorers_by_season',
  'football_get_topscorers_by_stage',
  'football_get_transfer',
  'football_get_transfer_rumour',
  'football_get_transfer_rumours_between_dates',
  'football_get_transfer_rumours_by_player',
  'football_get_transfer_rumours_by_team',
  'football_get_transfers_between_dates',
  'football_get_transfers_by_player',
  'football_get_transfers_by_team',
  'football_get_tv_station',
  'football_get_tv_stations',
  'football_get_tv_stations_by_fixture',
  'football_get_upcoming_fixtures_by_market',
  'football_get_upcoming_fixtures_by_tv_station',
  'football_get_venue',
  'football_get_venues',
  'football_get_venues_by_season',
  'football_search_coaches',
  'football_search_fixtures',
  'football_search_leagues',
  'football_search_players',
  'football_search_referees',
  'football_search_rounds',
  'football_search_seasons',
  'football_search_stages',
  'football_search_teams',
  'football_search_venues',
  'motorsport_get_all_fixtures',
  'motorsport_get_current_leagues_by_team',
  'motorsport_get_driver',
  'motorsport_get_driver_standings',
  'motorsport_get_driver_standings_by_season',
  'motorsport_get_drivers',
  'motorsport_get_drivers_by_country',
  'motorsport_get_drivers_by_season',
  'motorsport_get_fixture',
  'motorsport_get_fixtures_by_date',
  'motorsport_get_fixtures_by_date_range',
  'motorsport_get_fixtures_by_ids',
  'motorsport_get_laps_by_fixture',
  'motorsport_get_laps_by_fixture_and_driver',
  'motorsport_get_laps_by_fixture_and_lap',
  'motorsport_get_latest_laps_by_fixture',
  'motorsport_get_latest_pitstops_by_fixture',
  'motorsport_get_latest_stints_by_fixture',
  'motorsport_get_latest_updated_drivers',
  'motorsport_get_latest_updated_fixtures',
  'motorsport_get_league',
  'motorsport_get_leagues',
  'motorsport_get_leagues_by_country',
  'motorsport_get_leagues_by_date',
  'motorsport_get_leagues_by_live',
  'motorsport_get_leagues_by_team',
  'motorsport_get_livescores',
  'motorsport_get_pitstops_by_fixture',
  'motorsport_get_pitstops_by_fixture_and_driver',
  'motorsport_get_pitstops_by_fixture_and_lap',
  'motorsport_get_race_results_by_season_and_driver',
  'motorsport_get_race_results_by_season_and_team',
  'motorsport_get_schedules_by_season',
  'motorsport_get_season',
  'motorsport_get_seasons',
  'motorsport_get_stage',
  'motorsport_get_stages',
  'motorsport_get_stages_by_season',
  'motorsport_get_state',
  'motorsport_get_states',
  'motorsport_get_stints_by_fixture',
  'motorsport_get_stints_by_fixture_and_driver',
  'motorsport_get_stints_by_fixture_and_stint',
  'motorsport_get_team',
  'motorsport_get_team_standings',
  'motorsport_get_team_standings_by_season',
  'motorsport_get_teams',
  'motorsport_get_teams_by_country',
  'motorsport_get_teams_by_season',
  'motorsport_get_venue',
  'motorsport_get_venues',
  'motorsport_get_venues_by_season',
  'motorsport_search_drivers',
  'motorsport_search_leagues',
  'motorsport_search_stages',
  'motorsport_search_teams',
  'motorsport_search_venues',
  'odds_get_all_historical_odds',
  'odds_get_all_inplay_odds',
  'odds_get_all_pre_match_odds',
  'odds_get_all_premium_odds',
  'odds_get_bookmakers',
  'odds_get_inplay_odds_by_fixture',
  'odds_get_inplay_odds_by_fixture_and_bookmaker',
  'odds_get_inplay_odds_by_fixture_and_market',
  'odds_get_last_updated_inplay_odds',
  'odds_get_last_updated_pre_match_odds',
  'odds_get_markets',
  'odds_get_pre_match_odds_by_fixture',
  'odds_get_pre_match_odds_by_fixture_and_bookmaker',
  'odds_get_pre_match_odds_by_fixture_and_market',
  'odds_get_premium_odds_by_fixture',
  'odds_get_premium_odds_by_fixture_and_bookmaker',
  'odds_get_premium_odds_by_fixture_and_market',
  'odds_get_updated_historical_odds_between',
  'odds_get_updated_premium_odds_between',
]

const PAGINATED_OPS = [
  'football_get_totw',
  'core_get_cities',
  'core_get_continents',
  'core_get_countries',
  'core_get_my_usage',
  'core_get_regions',
  'core_get_types',
  'core_search_cities',
  'core_search_countries',
  'core_search_regions',
  'football_expected_by_player',
  'football_expected_by_team',
  'football_get_all_commentaries',
  'football_get_all_fixtures',
  'football_get_all_players',
  'football_get_all_rivals',
  'football_get_all_teams',
  'football_get_all_transfer_rumours',
  'football_get_all_transfers',
  'football_get_coaches',
  'football_get_coaches_by_country',
  'football_get_current_leagues_by_team',
  'football_get_expected_lineups_by_player',
  'football_get_expected_lineups_by_team',
  'football_get_fixtures_by_date',
  'football_get_fixtures_by_date_range',
  'football_get_fixtures_by_date_range_for_team',
  'football_get_head_to_head',
  'football_get_latest_coaches',
  'football_get_latest_transfers',
  'football_get_leagues',
  'football_get_leagues_by_country',
  'football_get_leagues_by_date',
  'football_get_leagues_by_team',
  'football_get_live_leagues',
  'football_get_live_probabilities',
  'football_get_live_probabilities_by_fixture',
  'football_get_match_facts',
  'football_get_match_facts_by_date_range',
  'football_get_match_facts_by_fixture',
  'football_get_match_facts_by_league',
  'football_get_past_fixtures_by_tv_station',
  'football_get_players_by_country',
  'football_get_postmatch_news',
  'football_get_postmatch_news_by_season',
  'football_get_predictability_by_league',
  'football_get_prematch_news',
  'football_get_prematch_news_by_season',
  'football_get_prematch_news_upcoming',
  'football_get_probabilities',
  'football_get_probabilities_by_fixture',
  'football_get_referees',
  'football_get_referees_by_country',
  'football_get_referees_by_season',
  'football_get_round_statistics',
  'football_get_rounds',
  'football_get_seasons',
  'football_get_stage_statistics',
  'football_get_stages',
  'football_get_standings',
  'football_get_states',
  'football_get_team_rankings',
  'football_get_team_rankings_by_date',
  'football_get_team_rankings_by_team',
  'football_get_teams_by_country',
  'football_get_teams_by_season',
  'football_get_topscorers_by_season',
  'football_get_topscorers_by_stage',
  'football_get_transfer_rumours_between_dates',
  'football_get_transfer_rumours_by_player',
  'football_get_transfer_rumours_by_team',
  'football_get_transfers_between_dates',
  'football_get_transfers_by_player',
  'football_get_transfers_by_team',
  'football_get_tv_stations',
  'football_get_tv_stations_by_fixture',
  'football_get_upcoming_fixtures_by_market',
  'football_get_upcoming_fixtures_by_tv_station',
  'football_get_value_bets',
  'football_get_value_bets_by_fixture',
  'football_get_venues',
  'football_search_coaches',
  'football_search_fixtures',
  'football_search_leagues',
  'football_search_players',
  'football_search_referees',
  'football_search_rounds',
  'football_search_seasons',
  'football_search_stages',
  'football_search_teams',
  'football_search_venues',
  'motorsport_get_all_fixtures',
  'motorsport_get_current_leagues_by_team',
  'motorsport_get_driver_standings',
  'motorsport_get_driver_standings_by_season',
  'motorsport_get_drivers',
  'motorsport_get_drivers_by_country',
  'motorsport_get_drivers_by_season',
  'motorsport_get_fixtures_by_date',
  'motorsport_get_fixtures_by_date_range',
  'motorsport_get_fixtures_by_ids',
  'motorsport_get_latest_updated_drivers',
  'motorsport_get_latest_updated_fixtures',
  'motorsport_get_leagues',
  'motorsport_get_leagues_by_country',
  'motorsport_get_leagues_by_date',
  'motorsport_get_leagues_by_live',
  'motorsport_get_leagues_by_team',
  'motorsport_get_livescores',
  'motorsport_get_race_results_by_season_and_driver',
  'motorsport_get_race_results_by_season_and_team',
  'motorsport_get_schedules_by_season',
  'motorsport_get_seasons',
  'motorsport_get_stages',
  'motorsport_get_stages_by_season',
  'motorsport_get_states',
  'motorsport_get_team_standings',
  'motorsport_get_team_standings_by_season',
  'motorsport_get_teams',
  'motorsport_get_teams_by_country',
  'motorsport_get_teams_by_season',
  'motorsport_get_venues',
  'motorsport_get_venues_by_season',
  'motorsport_search_drivers',
  'motorsport_search_leagues',
  'motorsport_search_stages',
  'motorsport_search_teams',
  'motorsport_search_venues',
  'odds_get_all_historical_odds',
  'odds_get_all_inplay_odds',
  'odds_get_all_pre_match_odds',
  'odds_get_all_premium_odds',
  'odds_get_bookmaker_event_ids_by_fixture',
  'odds_get_bookmakers',
  'odds_get_bookmakers_by_fixture',
  'odds_get_inplay_odds_by_fixture',
  'odds_get_markets',
  'odds_get_pre_match_odds_by_fixture',
  'odds_get_updated_historical_odds_between',
  'odds_get_updated_premium_odds_between',
  'odds_search_bookmakers',
  'odds_search_markets',
]

const BOOKMAKER_ID_OPS = [
  'odds_get_bookmaker',
  'odds_get_inplay_odds_by_fixture_and_bookmaker',
  'odds_get_pre_match_odds_by_fixture_and_bookmaker',
  'odds_get_premium_odds_by_fixture_and_bookmaker',
]

const CITY_ID_OPS = ['core_get_city']

const COACH_ID_OPS = ['football_get_coach']

const CONTINENT_ID_OPS = ['core_get_continent']

const COUNTRY_ID_OPS = [
  'core_get_country',
  'football_get_coaches_by_country',
  'football_get_leagues_by_country',
  'football_get_players_by_country',
  'football_get_referees_by_country',
  'football_get_teams_by_country',
  'motorsport_get_drivers_by_country',
  'motorsport_get_leagues_by_country',
  'motorsport_get_teams_by_country',
]

const DATE_OPS = [
  'football_get_fixtures_by_date',
  'football_get_leagues_by_date',
  'football_get_team_rankings_by_date',
  'motorsport_get_fixtures_by_date',
  'motorsport_get_leagues_by_date',
]

const DRIVER_ID_OPS = [
  'motorsport_get_driver',
  'motorsport_get_laps_by_fixture_and_driver',
  'motorsport_get_pitstops_by_fixture_and_driver',
  'motorsport_get_race_results_by_season_and_driver',
  'motorsport_get_stints_by_fixture_and_driver',
]

const END_DATE_OPS = [
  'football_get_fixtures_by_date_range',
  'football_get_fixtures_by_date_range_for_team',
  'football_get_match_facts_by_date_range',
  'football_get_transfer_rumours_between_dates',
  'football_get_transfers_between_dates',
  'motorsport_get_fixtures_by_date_range',
]

const FIXTURE_ID_OPS = [
  'football_get_commentaries_by_fixture',
  'football_get_fixture',
  'football_get_live_probabilities_by_fixture',
  'football_get_match_facts_by_fixture',
  'football_get_probabilities_by_fixture',
  'football_get_tv_stations_by_fixture',
  'football_get_value_bets_by_fixture',
  'motorsport_get_fixture',
  'motorsport_get_laps_by_fixture',
  'motorsport_get_laps_by_fixture_and_driver',
  'motorsport_get_laps_by_fixture_and_lap',
  'motorsport_get_latest_laps_by_fixture',
  'motorsport_get_latest_pitstops_by_fixture',
  'motorsport_get_latest_stints_by_fixture',
  'motorsport_get_pitstops_by_fixture',
  'motorsport_get_pitstops_by_fixture_and_driver',
  'motorsport_get_pitstops_by_fixture_and_lap',
  'motorsport_get_stints_by_fixture',
  'motorsport_get_stints_by_fixture_and_driver',
  'motorsport_get_stints_by_fixture_and_stint',
  'odds_get_bookmaker_event_ids_by_fixture',
  'odds_get_bookmakers_by_fixture',
  'odds_get_inplay_odds_by_fixture',
  'odds_get_inplay_odds_by_fixture_and_bookmaker',
  'odds_get_inplay_odds_by_fixture_and_market',
  'odds_get_pre_match_odds_by_fixture',
  'odds_get_pre_match_odds_by_fixture_and_bookmaker',
  'odds_get_pre_match_odds_by_fixture_and_market',
  'odds_get_premium_odds_by_fixture',
  'odds_get_premium_odds_by_fixture_and_bookmaker',
  'odds_get_premium_odds_by_fixture_and_market',
]

const FIXTURE_IDS_OPS = ['motorsport_get_fixtures_by_ids']

const FROM_TIMESTAMP_OPS = [
  'odds_get_updated_historical_odds_between',
  'odds_get_updated_premium_odds_between',
]

const IDS_OPS = ['football_get_fixtures_by_ids']

const LAP_NUMBER_OPS = [
  'motorsport_get_laps_by_fixture_and_lap',
  'motorsport_get_pitstops_by_fixture_and_lap',
]

const LEAGUE_ID_OPS = [
  'football_get_latest_totw',
  'football_get_league',
  'football_get_live_standings_by_league',
  'football_get_match_facts_by_league',
  'football_get_predictability_by_league',
  'motorsport_get_league',
]

const MARKET_ID_OPS = [
  'football_get_upcoming_fixtures_by_market',
  'odds_get_inplay_odds_by_fixture_and_market',
  'odds_get_market',
  'odds_get_pre_match_odds_by_fixture_and_market',
  'odds_get_premium_odds_by_fixture_and_market',
]

const PLAYER_ID_OPS = [
  'football_get_expected_lineups_by_player',
  'football_get_player',
  'football_get_transfer_rumours_by_player',
  'football_get_transfers_by_player',
]

const QUERY_OPS = [
  'core_search_cities',
  'core_search_countries',
  'core_search_regions',
  'football_search_coaches',
  'football_search_fixtures',
  'football_search_leagues',
  'football_search_players',
  'football_search_referees',
  'football_search_rounds',
  'football_search_seasons',
  'football_search_stages',
  'football_search_teams',
  'football_search_venues',
  'motorsport_search_drivers',
  'motorsport_search_leagues',
  'motorsport_search_stages',
  'motorsport_search_teams',
  'motorsport_search_venues',
  'odds_search_bookmakers',
  'odds_search_markets',
]

const REFEREE_ID_OPS = ['football_get_referee']

const REGION_ID_OPS = ['core_get_region']

const ROUND_ID_OPS = [
  'football_get_grouped_standings_by_round',
  'football_get_round',
  'football_get_round_statistics',
  'football_get_standings_by_round',
  'football_get_totw_by_round',
]

const RUMOUR_ID_OPS = ['football_get_transfer_rumour']

const SEASON_ID_OPS = [
  'football_get_brackets_by_season',
  'football_get_postmatch_news_by_season',
  'football_get_prematch_news_by_season',
  'football_get_referees_by_season',
  'football_get_rounds_by_season',
  'football_get_schedules_by_season',
  'football_get_schedules_by_season_and_team',
  'football_get_season',
  'football_get_stages_by_season',
  'football_get_standing_corrections_by_season',
  'football_get_standings_by_season',
  'football_get_team_squad_by_season',
  'football_get_teams_by_season',
  'football_get_topscorers_by_season',
  'football_get_venues_by_season',
  'motorsport_get_driver_standings_by_season',
  'motorsport_get_drivers_by_season',
  'motorsport_get_race_results_by_season_and_driver',
  'motorsport_get_race_results_by_season_and_team',
  'motorsport_get_schedules_by_season',
  'motorsport_get_season',
  'motorsport_get_stages_by_season',
  'motorsport_get_team_standings_by_season',
  'motorsport_get_teams_by_season',
  'motorsport_get_venues_by_season',
]

const STAGE_ID_OPS = [
  'football_get_stage',
  'football_get_stage_statistics',
  'football_get_topscorers_by_stage',
  'motorsport_get_stage',
]

const START_DATE_OPS = [
  'football_get_fixtures_by_date_range',
  'football_get_fixtures_by_date_range_for_team',
  'football_get_match_facts_by_date_range',
  'football_get_transfer_rumours_between_dates',
  'football_get_transfers_between_dates',
  'motorsport_get_fixtures_by_date_range',
]

const STATE_ID_OPS = ['football_get_state', 'motorsport_get_state']

const STINT_NUMBER_OPS = ['motorsport_get_stints_by_fixture_and_stint']

const TEAM_1_OPS = ['football_get_head_to_head']

const TEAM_2_OPS = ['football_get_head_to_head']

const TEAM_ID_OPS = [
  'football_get_team',
  'football_get_current_leagues_by_team',
  'football_get_expected_lineups_by_team',
  'football_get_extended_team_squad',
  'football_get_fixtures_by_date_range_for_team',
  'football_get_leagues_by_team',
  'football_get_rivals_by_team',
  'football_get_schedules_by_season_and_team',
  'football_get_schedules_by_team',
  'football_get_seasons_by_team',
  'football_get_team_rankings_by_team',
  'football_get_team_squad',
  'football_get_team_squad_by_season',
  'football_get_transfer_rumours_by_team',
  'football_get_transfers_by_team',
  'motorsport_get_current_leagues_by_team',
  'motorsport_get_leagues_by_team',
  'motorsport_get_race_results_by_season_and_team',
  'motorsport_get_team',
]

const TO_TIMESTAMP_OPS = [
  'odds_get_updated_historical_odds_between',
  'odds_get_updated_premium_odds_between',
]

const TRANSFER_ID_OPS = ['football_get_transfer']

const TV_STATION_ID_OPS = [
  'football_get_past_fixtures_by_tv_station',
  'football_get_tv_station',
  'football_get_upcoming_fixtures_by_tv_station',
]

const TYPE_ID_OPS = ['core_get_type']

const VENUE_ID_OPS = ['football_get_venue', 'motorsport_get_venue']

export const SportmonksBlock: BlockConfig = {
  type: 'sportmonks',
  name: 'Sportmonks',
  description: 'Access Sportmonks football, motorsport, odds, and reference data',
  longDescription:
    'Integrate the Sportmonks sports data APIs into the workflow from a single block. Football: fixtures, livescores, leagues, seasons, stages, rounds, teams, squads, players, coaches, referees, venues, standings, topscorers, transfers, schedules, commentaries, TV stations, rivals, expected goals (xG), and predictions. Motorsport: sessions, drivers, teams, championship standings, laps, and pitstops. Odds: pre-match and in-play odds, bookmakers, and markets. Core: continents, countries, regions, cities, types, and time zones.',
  docsLink: 'https://docs.sim.ai/integrations/sportmonks',
  category: 'tools',
  integrationType: IntegrationType.Analytics,
  bgColor: '#171534',
  icon: SportmonksIcon,
  authMode: AuthMode.ApiKey,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      options: [
        {
          label: 'Football: Get Expected xG by Player',
          id: 'football_expected_by_player',
          group: 'Football',
        },
        {
          label: 'Football: Get Expected xG by Team',
          id: 'football_expected_by_team',
          group: 'Football',
        },
        {
          label: 'Football: Get All Commentaries',
          id: 'football_get_all_commentaries',
          group: 'Football',
        },
        { label: 'Football: Get All Fixtures', id: 'football_get_all_fixtures', group: 'Football' },
        { label: 'Football: Get All Players', id: 'football_get_all_players', group: 'Football' },
        { label: 'Football: Get All Rivals', id: 'football_get_all_rivals', group: 'Football' },
        { label: 'Football: Get All Teams', id: 'football_get_all_teams', group: 'Football' },
        {
          label: 'Football: Get All Transfer Rumours',
          id: 'football_get_all_transfer_rumours',
          group: 'Football',
        },
        {
          label: 'Football: Get All Transfers',
          id: 'football_get_all_transfers',
          group: 'Football',
        },
        {
          label: 'Football: Get Brackets by Season',
          id: 'football_get_brackets_by_season',
          group: 'Football',
        },
        { label: 'Football: Get Coach by ID', id: 'football_get_coach', group: 'Football' },
        { label: 'Football: Get Coaches', id: 'football_get_coaches', group: 'Football' },
        {
          label: 'Football: Get Coaches by Country',
          id: 'football_get_coaches_by_country',
          group: 'Football',
        },
        {
          label: 'Football: Get Commentaries by Fixture',
          id: 'football_get_commentaries_by_fixture',
          group: 'Football',
        },
        {
          label: 'Football: Get Current Leagues by Team',
          id: 'football_get_current_leagues_by_team',
          group: 'Football',
        },
        {
          label: 'Football: Get Expected Lineups by Player',
          id: 'football_get_expected_lineups_by_player',
          group: 'Football',
        },
        {
          label: 'Football: Get Expected Lineups by Team',
          id: 'football_get_expected_lineups_by_team',
          group: 'Football',
        },
        {
          label: 'Football: Get Extended Team Squad',
          id: 'football_get_extended_team_squad',
          group: 'Football',
        },
        { label: 'Football: Get Fixture by ID', id: 'football_get_fixture', group: 'Football' },
        {
          label: 'Football: Get Fixtures by Date',
          id: 'football_get_fixtures_by_date',
          group: 'Football',
        },
        {
          label: 'Football: Get Fixtures by Date Range',
          id: 'football_get_fixtures_by_date_range',
          group: 'Football',
        },
        {
          label: 'Football: Get Fixtures by Date Range for Team',
          id: 'football_get_fixtures_by_date_range_for_team',
          group: 'Football',
        },
        {
          label: 'Football: Get Fixtures by Multiple IDs',
          id: 'football_get_fixtures_by_ids',
          group: 'Football',
        },
        {
          label: 'Football: Get Grouped Standings by Round',
          id: 'football_get_grouped_standings_by_round',
          group: 'Football',
        },
        { label: 'Football: Get Head to Head', id: 'football_get_head_to_head', group: 'Football' },
        {
          label: 'Football: Get Inplay Livescores',
          id: 'football_get_inplay_livescores',
          group: 'Football',
        },
        {
          label: 'Football: Get Last Updated Coaches',
          id: 'football_get_latest_coaches',
          group: 'Football',
        },
        {
          label: 'Football: Get Latest Updated Fixtures',
          id: 'football_get_latest_fixtures',
          group: 'Football',
        },
        {
          label: 'Football: Get Latest Updated Livescores',
          id: 'football_get_latest_livescores',
          group: 'Football',
        },
        {
          label: 'Football: Get Last Updated Players',
          id: 'football_get_latest_players',
          group: 'Football',
        },
        {
          label: 'Football: Get Latest Team of the Week',
          id: 'football_get_latest_totw',
          group: 'Football',
        },
        {
          label: 'Football: Get Latest Transfers',
          id: 'football_get_latest_transfers',
          group: 'Football',
        },
        { label: 'Football: Get League by ID', id: 'football_get_league', group: 'Football' },
        { label: 'Football: Get Leagues', id: 'football_get_leagues', group: 'Football' },
        {
          label: 'Football: Get Leagues by Country',
          id: 'football_get_leagues_by_country',
          group: 'Football',
        },
        {
          label: 'Football: Get Leagues by Date',
          id: 'football_get_leagues_by_date',
          group: 'Football',
        },
        {
          label: 'Football: Get Leagues by Team',
          id: 'football_get_leagues_by_team',
          group: 'Football',
        },
        { label: 'Football: Get Live Leagues', id: 'football_get_live_leagues', group: 'Football' },
        {
          label: 'Football: Get Live Probabilities',
          id: 'football_get_live_probabilities',
          group: 'Football',
        },
        {
          label: 'Football: Get Live Probabilities by Fixture',
          id: 'football_get_live_probabilities_by_fixture',
          group: 'Football',
        },
        {
          label: 'Football: Get Live Standings by League',
          id: 'football_get_live_standings_by_league',
          group: 'Football',
        },
        { label: 'Football: Get Livescores', id: 'football_get_livescores', group: 'Football' },
        {
          label: 'Football: Get All Match Facts',
          id: 'football_get_match_facts',
          group: 'Football',
        },
        {
          label: 'Football: Get Match Facts by Date Range',
          id: 'football_get_match_facts_by_date_range',
          group: 'Football',
        },
        {
          label: 'Football: Get Match Facts by Fixture',
          id: 'football_get_match_facts_by_fixture',
          group: 'Football',
        },
        {
          label: 'Football: Get Match Facts by League',
          id: 'football_get_match_facts_by_league',
          group: 'Football',
        },
        {
          label: 'Football: Get Past Fixtures by TV Station',
          id: 'football_get_past_fixtures_by_tv_station',
          group: 'Football',
        },
        { label: 'Football: Get Player by ID', id: 'football_get_player', group: 'Football' },
        {
          label: 'Football: Get Players by Country',
          id: 'football_get_players_by_country',
          group: 'Football',
        },
        {
          label: 'Football: Get Post-Match News',
          id: 'football_get_postmatch_news',
          group: 'Football',
        },
        {
          label: 'Football: Get Post-Match News by Season',
          id: 'football_get_postmatch_news_by_season',
          group: 'Football',
        },
        {
          label: 'Football: Get Predictability by League',
          id: 'football_get_predictability_by_league',
          group: 'Football',
        },
        {
          label: 'Football: Get Pre-Match News',
          id: 'football_get_prematch_news',
          group: 'Football',
        },
        {
          label: 'Football: Get Pre-Match News by Season',
          id: 'football_get_prematch_news_by_season',
          group: 'Football',
        },
        {
          label: 'Football: Get Pre-Match News for Upcoming Fixtures',
          id: 'football_get_prematch_news_upcoming',
          group: 'Football',
        },
        {
          label: 'Football: Get Probabilities',
          id: 'football_get_probabilities',
          group: 'Football',
        },
        {
          label: 'Football: Get Predictions by Fixture',
          id: 'football_get_probabilities_by_fixture',
          group: 'Football',
        },
        { label: 'Football: Get Referee by ID', id: 'football_get_referee', group: 'Football' },
        { label: 'Football: Get Referees', id: 'football_get_referees', group: 'Football' },
        {
          label: 'Football: Get Referees by Country',
          id: 'football_get_referees_by_country',
          group: 'Football',
        },
        {
          label: 'Football: Get Referees by Season',
          id: 'football_get_referees_by_season',
          group: 'Football',
        },
        {
          label: 'Football: Get Rivals by Team',
          id: 'football_get_rivals_by_team',
          group: 'Football',
        },
        { label: 'Football: Get Round by ID', id: 'football_get_round', group: 'Football' },
        {
          label: 'Football: Get Round Statistics',
          id: 'football_get_round_statistics',
          group: 'Football',
        },
        { label: 'Football: Get Rounds', id: 'football_get_rounds', group: 'Football' },
        {
          label: 'Football: Get Rounds by Season',
          id: 'football_get_rounds_by_season',
          group: 'Football',
        },
        {
          label: 'Football: Get Schedules by Season',
          id: 'football_get_schedules_by_season',
          group: 'Football',
        },
        {
          label: 'Football: Get Schedules by Season and Team',
          id: 'football_get_schedules_by_season_and_team',
          group: 'Football',
        },
        {
          label: 'Football: Get Schedules by Team',
          id: 'football_get_schedules_by_team',
          group: 'Football',
        },
        { label: 'Football: Get Season by ID', id: 'football_get_season', group: 'Football' },
        { label: 'Football: Get Seasons', id: 'football_get_seasons', group: 'Football' },
        {
          label: 'Football: Get Seasons by Team',
          id: 'football_get_seasons_by_team',
          group: 'Football',
        },
        { label: 'Football: Get Stage by ID', id: 'football_get_stage', group: 'Football' },
        {
          label: 'Football: Get Stage Statistics',
          id: 'football_get_stage_statistics',
          group: 'Football',
        },
        { label: 'Football: Get Stages', id: 'football_get_stages', group: 'Football' },
        {
          label: 'Football: Get Stages by Season',
          id: 'football_get_stages_by_season',
          group: 'Football',
        },
        {
          label: 'Football: Get Standing Corrections by Season',
          id: 'football_get_standing_corrections_by_season',
          group: 'Football',
        },
        { label: 'Football: Get All Standings', id: 'football_get_standings', group: 'Football' },
        {
          label: 'Football: Get Standings by Round',
          id: 'football_get_standings_by_round',
          group: 'Football',
        },
        {
          label: 'Football: Get Standings by Season',
          id: 'football_get_standings_by_season',
          group: 'Football',
        },
        { label: 'Football: Get State by ID', id: 'football_get_state', group: 'Football' },
        { label: 'Football: Get States', id: 'football_get_states', group: 'Football' },
        { label: 'Football: Get Team by ID', id: 'football_get_team', group: 'Football' },
        {
          label: 'Football: Get All Team Rankings',
          id: 'football_get_team_rankings',
          group: 'Football',
        },
        {
          label: 'Football: Get Team Rankings by Date',
          id: 'football_get_team_rankings_by_date',
          group: 'Football',
        },
        {
          label: 'Football: Get Team Rankings by Team',
          id: 'football_get_team_rankings_by_team',
          group: 'Football',
        },
        { label: 'Football: Get Team Squad', id: 'football_get_team_squad', group: 'Football' },
        {
          label: 'Football: Get Team Squad by Season',
          id: 'football_get_team_squad_by_season',
          group: 'Football',
        },
        {
          label: 'Football: Get Teams by Country',
          id: 'football_get_teams_by_country',
          group: 'Football',
        },
        {
          label: 'Football: Get Teams by Season',
          id: 'football_get_teams_by_season',
          group: 'Football',
        },
        {
          label: 'Football: Get Topscorers by Season',
          id: 'football_get_topscorers_by_season',
          group: 'Football',
        },
        {
          label: 'Football: Get Topscorers by Stage',
          id: 'football_get_topscorers_by_stage',
          group: 'Football',
        },
        { label: 'Football: Get All Team of the Week', id: 'football_get_totw', group: 'Football' },
        {
          label: 'Football: Get Team of the Week by Round',
          id: 'football_get_totw_by_round',
          group: 'Football',
        },
        { label: 'Football: Get Transfer by ID', id: 'football_get_transfer', group: 'Football' },
        {
          label: 'Football: Get Transfer Rumour by ID',
          id: 'football_get_transfer_rumour',
          group: 'Football',
        },
        {
          label: 'Football: Get Transfer Rumours Between Dates',
          id: 'football_get_transfer_rumours_between_dates',
          group: 'Football',
        },
        {
          label: 'Football: Get Transfer Rumours by Player',
          id: 'football_get_transfer_rumours_by_player',
          group: 'Football',
        },
        {
          label: 'Football: Get Transfer Rumours by Team',
          id: 'football_get_transfer_rumours_by_team',
          group: 'Football',
        },
        {
          label: 'Football: Get Transfers Between Dates',
          id: 'football_get_transfers_between_dates',
          group: 'Football',
        },
        {
          label: 'Football: Get Transfers by Player',
          id: 'football_get_transfers_by_player',
          group: 'Football',
        },
        {
          label: 'Football: Get Transfers by Team',
          id: 'football_get_transfers_by_team',
          group: 'Football',
        },
        {
          label: 'Football: Get TV Station by ID',
          id: 'football_get_tv_station',
          group: 'Football',
        },
        { label: 'Football: Get TV Stations', id: 'football_get_tv_stations', group: 'Football' },
        {
          label: 'Football: Get TV Stations by Fixture',
          id: 'football_get_tv_stations_by_fixture',
          group: 'Football',
        },
        {
          label: 'Football: Get Upcoming Fixtures by Market',
          id: 'football_get_upcoming_fixtures_by_market',
          group: 'Football',
        },
        {
          label: 'Football: Get Upcoming Fixtures by TV Station',
          id: 'football_get_upcoming_fixtures_by_tv_station',
          group: 'Football',
        },
        { label: 'Football: Get Value Bets', id: 'football_get_value_bets', group: 'Football' },
        {
          label: 'Football: Get Value Bets by Fixture',
          id: 'football_get_value_bets_by_fixture',
          group: 'Football',
        },
        { label: 'Football: Get Venue by ID', id: 'football_get_venue', group: 'Football' },
        { label: 'Football: Get Venues', id: 'football_get_venues', group: 'Football' },
        {
          label: 'Football: Get Venues by Season',
          id: 'football_get_venues_by_season',
          group: 'Football',
        },
        { label: 'Football: Search Coaches', id: 'football_search_coaches', group: 'Football' },
        { label: 'Football: Search Fixtures', id: 'football_search_fixtures', group: 'Football' },
        { label: 'Football: Search Leagues', id: 'football_search_leagues', group: 'Football' },
        { label: 'Football: Search Players', id: 'football_search_players', group: 'Football' },
        { label: 'Football: Search Referees', id: 'football_search_referees', group: 'Football' },
        { label: 'Football: Search Rounds', id: 'football_search_rounds', group: 'Football' },
        { label: 'Football: Search Seasons', id: 'football_search_seasons', group: 'Football' },
        { label: 'Football: Search Stages', id: 'football_search_stages', group: 'Football' },
        { label: 'Football: Search Teams', id: 'football_search_teams', group: 'Football' },
        { label: 'Football: Search Venues', id: 'football_search_venues', group: 'Football' },
        {
          label: 'Motorsport: Get All Fixtures',
          id: 'motorsport_get_all_fixtures',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Current Leagues by Team',
          id: 'motorsport_get_current_leagues_by_team',
          group: 'Motorsport',
        },
        { label: 'Motorsport: Get Driver by ID', id: 'motorsport_get_driver', group: 'Motorsport' },
        {
          label: 'Motorsport: Get All Driver Standings',
          id: 'motorsport_get_driver_standings',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Driver Standings by Season',
          id: 'motorsport_get_driver_standings_by_season',
          group: 'Motorsport',
        },
        { label: 'Motorsport: Get Drivers', id: 'motorsport_get_drivers', group: 'Motorsport' },
        {
          label: 'Motorsport: Get Drivers by Country',
          id: 'motorsport_get_drivers_by_country',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Drivers by Season',
          id: 'motorsport_get_drivers_by_season',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Fixture by ID',
          id: 'motorsport_get_fixture',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Fixtures by Date',
          id: 'motorsport_get_fixtures_by_date',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Fixtures by Date Range',
          id: 'motorsport_get_fixtures_by_date_range',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Fixtures by IDs',
          id: 'motorsport_get_fixtures_by_ids',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Laps by Fixture',
          id: 'motorsport_get_laps_by_fixture',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Laps by Fixture and Driver',
          id: 'motorsport_get_laps_by_fixture_and_driver',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Laps by Fixture and Lap Number',
          id: 'motorsport_get_laps_by_fixture_and_lap',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Latest Laps by Fixture',
          id: 'motorsport_get_latest_laps_by_fixture',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Latest Pitstops by Fixture',
          id: 'motorsport_get_latest_pitstops_by_fixture',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Latest Stints by Fixture',
          id: 'motorsport_get_latest_stints_by_fixture',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Latest Updated Drivers',
          id: 'motorsport_get_latest_updated_drivers',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Latest Updated Fixtures',
          id: 'motorsport_get_latest_updated_fixtures',
          group: 'Motorsport',
        },
        { label: 'Motorsport: Get League by ID', id: 'motorsport_get_league', group: 'Motorsport' },
        { label: 'Motorsport: Get All Leagues', id: 'motorsport_get_leagues', group: 'Motorsport' },
        {
          label: 'Motorsport: Get Leagues by Country',
          id: 'motorsport_get_leagues_by_country',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Leagues by Fixture Date',
          id: 'motorsport_get_leagues_by_date',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Leagues by Live',
          id: 'motorsport_get_leagues_by_live',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Leagues by Team',
          id: 'motorsport_get_leagues_by_team',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Livescores',
          id: 'motorsport_get_livescores',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Pitstops by Fixture',
          id: 'motorsport_get_pitstops_by_fixture',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Pitstops by Fixture and Driver',
          id: 'motorsport_get_pitstops_by_fixture_and_driver',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Pitstops by Fixture and Lap Number',
          id: 'motorsport_get_pitstops_by_fixture_and_lap',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Race Results by Season and Driver',
          id: 'motorsport_get_race_results_by_season_and_driver',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Race Results by Season and Team',
          id: 'motorsport_get_race_results_by_season_and_team',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Schedules by Season',
          id: 'motorsport_get_schedules_by_season',
          group: 'Motorsport',
        },
        { label: 'Motorsport: Get Season by ID', id: 'motorsport_get_season', group: 'Motorsport' },
        { label: 'Motorsport: Get All Seasons', id: 'motorsport_get_seasons', group: 'Motorsport' },
        { label: 'Motorsport: Get Stage by ID', id: 'motorsport_get_stage', group: 'Motorsport' },
        { label: 'Motorsport: Get All Stages', id: 'motorsport_get_stages', group: 'Motorsport' },
        {
          label: 'Motorsport: Get Stages by Season',
          id: 'motorsport_get_stages_by_season',
          group: 'Motorsport',
        },
        { label: 'Motorsport: Get State by ID', id: 'motorsport_get_state', group: 'Motorsport' },
        { label: 'Motorsport: Get All States', id: 'motorsport_get_states', group: 'Motorsport' },
        {
          label: 'Motorsport: Get Stints by Fixture',
          id: 'motorsport_get_stints_by_fixture',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Stints by Fixture and Driver',
          id: 'motorsport_get_stints_by_fixture_and_driver',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Stints by Fixture and Stint Number',
          id: 'motorsport_get_stints_by_fixture_and_stint',
          group: 'Motorsport',
        },
        { label: 'Motorsport: Get Team by ID', id: 'motorsport_get_team', group: 'Motorsport' },
        {
          label: 'Motorsport: Get All Team Standings',
          id: 'motorsport_get_team_standings',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Team Standings by Season',
          id: 'motorsport_get_team_standings_by_season',
          group: 'Motorsport',
        },
        { label: 'Motorsport: Get Teams', id: 'motorsport_get_teams', group: 'Motorsport' },
        {
          label: 'Motorsport: Get Teams by Country',
          id: 'motorsport_get_teams_by_country',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Get Teams by Season',
          id: 'motorsport_get_teams_by_season',
          group: 'Motorsport',
        },
        { label: 'Motorsport: Get Venue by ID', id: 'motorsport_get_venue', group: 'Motorsport' },
        { label: 'Motorsport: Get Venues', id: 'motorsport_get_venues', group: 'Motorsport' },
        {
          label: 'Motorsport: Get Venues by Season',
          id: 'motorsport_get_venues_by_season',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Search Drivers',
          id: 'motorsport_search_drivers',
          group: 'Motorsport',
        },
        {
          label: 'Motorsport: Search Leagues',
          id: 'motorsport_search_leagues',
          group: 'Motorsport',
        },
        { label: 'Motorsport: Search Stages', id: 'motorsport_search_stages', group: 'Motorsport' },
        { label: 'Motorsport: Search Teams', id: 'motorsport_search_teams', group: 'Motorsport' },
        { label: 'Motorsport: Search Venues', id: 'motorsport_search_venues', group: 'Motorsport' },
        {
          label: 'Odds: Get All Historical Odds',
          id: 'odds_get_all_historical_odds',
          group: 'Odds',
        },
        { label: 'Odds: Get All In-play Odds', id: 'odds_get_all_inplay_odds', group: 'Odds' },
        { label: 'Odds: Get All Pre-match Odds', id: 'odds_get_all_pre_match_odds', group: 'Odds' },
        { label: 'Odds: Get All Premium Odds', id: 'odds_get_all_premium_odds', group: 'Odds' },
        { label: 'Odds: Get Bookmaker by ID', id: 'odds_get_bookmaker', group: 'Odds' },
        {
          label: 'Odds: Get Bookmaker Event IDs by Fixture',
          id: 'odds_get_bookmaker_event_ids_by_fixture',
          group: 'Odds',
        },
        { label: 'Odds: Get Bookmakers', id: 'odds_get_bookmakers', group: 'Odds' },
        {
          label: 'Odds: Get Bookmakers by Fixture',
          id: 'odds_get_bookmakers_by_fixture',
          group: 'Odds',
        },
        {
          label: 'Odds: Get In-play Odds by Fixture',
          id: 'odds_get_inplay_odds_by_fixture',
          group: 'Odds',
        },
        {
          label: 'Odds: Get In-play Odds by Fixture and Bookmaker',
          id: 'odds_get_inplay_odds_by_fixture_and_bookmaker',
          group: 'Odds',
        },
        {
          label: 'Odds: Get In-play Odds by Fixture and Market',
          id: 'odds_get_inplay_odds_by_fixture_and_market',
          group: 'Odds',
        },
        {
          label: 'Odds: Get Last Updated In-play Odds',
          id: 'odds_get_last_updated_inplay_odds',
          group: 'Odds',
        },
        {
          label: 'Odds: Get Last Updated Pre-match Odds',
          id: 'odds_get_last_updated_pre_match_odds',
          group: 'Odds',
        },
        { label: 'Odds: Get Market by ID', id: 'odds_get_market', group: 'Odds' },
        { label: 'Odds: Get Markets', id: 'odds_get_markets', group: 'Odds' },
        {
          label: 'Odds: Get Pre-match Odds by Fixture',
          id: 'odds_get_pre_match_odds_by_fixture',
          group: 'Odds',
        },
        {
          label: 'Odds: Get Pre-match Odds by Fixture and Bookmaker',
          id: 'odds_get_pre_match_odds_by_fixture_and_bookmaker',
          group: 'Odds',
        },
        {
          label: 'Odds: Get Pre-match Odds by Fixture and Market',
          id: 'odds_get_pre_match_odds_by_fixture_and_market',
          group: 'Odds',
        },
        {
          label: 'Odds: Get Premium Odds by Fixture',
          id: 'odds_get_premium_odds_by_fixture',
          group: 'Odds',
        },
        {
          label: 'Odds: Get Premium Odds by Fixture and Bookmaker',
          id: 'odds_get_premium_odds_by_fixture_and_bookmaker',
          group: 'Odds',
        },
        {
          label: 'Odds: Get Premium Odds by Fixture and Market',
          id: 'odds_get_premium_odds_by_fixture_and_market',
          group: 'Odds',
        },
        {
          label: 'Odds: Get Updated Historical Odds Between Time Range',
          id: 'odds_get_updated_historical_odds_between',
          group: 'Odds',
        },
        {
          label: 'Odds: Get Updated Premium Odds Between Time Range',
          id: 'odds_get_updated_premium_odds_between',
          group: 'Odds',
        },
        { label: 'Odds: Search Bookmakers', id: 'odds_search_bookmakers', group: 'Odds' },
        { label: 'Odds: Search Markets', id: 'odds_search_markets', group: 'Odds' },
        { label: 'Core: Get Cities', id: 'core_get_cities', group: 'Core (Reference)' },
        { label: 'Core: Get City by ID', id: 'core_get_city', group: 'Core (Reference)' },
        { label: 'Core: Get Continent by ID', id: 'core_get_continent', group: 'Core (Reference)' },
        { label: 'Core: Get Continents', id: 'core_get_continents', group: 'Core (Reference)' },
        { label: 'Core: Get Countries', id: 'core_get_countries', group: 'Core (Reference)' },
        { label: 'Core: Get Country by ID', id: 'core_get_country', group: 'Core (Reference)' },
        {
          label: 'Core: Get All Entity Filters',
          id: 'core_get_entity_filters',
          group: 'Core (Reference)',
        },
        { label: 'Core: Get My Usage', id: 'core_get_my_usage', group: 'Core (Reference)' },
        { label: 'Core: Get Region by ID', id: 'core_get_region', group: 'Core (Reference)' },
        { label: 'Core: Get Regions', id: 'core_get_regions', group: 'Core (Reference)' },
        { label: 'Core: Get Timezones', id: 'core_get_timezones', group: 'Core (Reference)' },
        { label: 'Core: Get Type by ID', id: 'core_get_type', group: 'Core (Reference)' },
        {
          label: 'Core: Get Type by Entity',
          id: 'core_get_type_by_entity',
          group: 'Core (Reference)',
        },
        { label: 'Core: Get Types', id: 'core_get_types', group: 'Core (Reference)' },
        { label: 'Core: Search Cities', id: 'core_search_cities', group: 'Core (Reference)' },
        { label: 'Core: Search Countries', id: 'core_search_countries', group: 'Core (Reference)' },
        { label: 'Core: Search Regions', id: 'core_search_regions', group: 'Core (Reference)' },
      ],
      value: () => 'football_get_fixtures_by_date',
    },
    {
      id: 'bookmakerId',
      title: 'Bookmaker ID',
      type: 'short-input',
      placeholder: 'Numeric bookmaker ID',
      condition: { field: 'operation', value: BOOKMAKER_ID_OPS },
      required: { field: 'operation', value: BOOKMAKER_ID_OPS },
    },
    {
      id: 'cityId',
      title: 'City ID',
      type: 'short-input',
      placeholder: 'Numeric city ID',
      condition: { field: 'operation', value: CITY_ID_OPS },
      required: { field: 'operation', value: CITY_ID_OPS },
    },
    {
      id: 'coachId',
      title: 'Coach ID',
      type: 'short-input',
      placeholder: 'Numeric coach ID',
      condition: { field: 'operation', value: COACH_ID_OPS },
      required: { field: 'operation', value: COACH_ID_OPS },
    },
    {
      id: 'continentId',
      title: 'Continent ID',
      type: 'short-input',
      placeholder: 'Numeric continent ID',
      condition: { field: 'operation', value: CONTINENT_ID_OPS },
      required: { field: 'operation', value: CONTINENT_ID_OPS },
    },
    {
      id: 'countryId',
      title: 'Country ID',
      type: 'short-input',
      placeholder: 'Numeric country ID',
      condition: { field: 'operation', value: COUNTRY_ID_OPS },
      required: { field: 'operation', value: COUNTRY_ID_OPS },
    },
    {
      id: 'date',
      title: 'Date',
      type: 'short-input',
      placeholder: 'YYYY-MM-DD',
      wandConfig: DATE_WAND_CONFIG,
      condition: { field: 'operation', value: DATE_OPS },
      required: { field: 'operation', value: DATE_OPS },
    },
    {
      id: 'driverId',
      title: 'Driver ID',
      type: 'short-input',
      placeholder: 'Numeric driver ID',
      condition: { field: 'operation', value: DRIVER_ID_OPS },
      required: { field: 'operation', value: DRIVER_ID_OPS },
    },
    {
      id: 'endDate',
      title: 'End Date',
      type: 'short-input',
      placeholder: 'YYYY-MM-DD',
      wandConfig: DATE_WAND_CONFIG,
      condition: { field: 'operation', value: END_DATE_OPS },
      required: { field: 'operation', value: END_DATE_OPS },
    },
    {
      id: 'fixtureId',
      title: 'Fixture ID',
      type: 'short-input',
      placeholder: 'Numeric fixture ID',
      condition: { field: 'operation', value: FIXTURE_ID_OPS },
      required: { field: 'operation', value: FIXTURE_ID_OPS },
    },
    {
      id: 'fixtureIds',
      title: 'Fixture IDs',
      type: 'short-input',
      placeholder: 'Comma-separated fixture IDs',
      condition: { field: 'operation', value: FIXTURE_IDS_OPS },
      required: { field: 'operation', value: FIXTURE_IDS_OPS },
    },
    {
      id: 'fromTimestamp',
      title: 'From (UNIX timestamp)',
      type: 'short-input',
      placeholder: 'Start UNIX timestamp',
      condition: { field: 'operation', value: FROM_TIMESTAMP_OPS },
      required: { field: 'operation', value: FROM_TIMESTAMP_OPS },
    },
    {
      id: 'ids',
      title: 'IDs',
      type: 'short-input',
      placeholder: 'Comma-separated IDs',
      condition: { field: 'operation', value: IDS_OPS },
      required: { field: 'operation', value: IDS_OPS },
    },
    {
      id: 'lapNumber',
      title: 'Lap Number',
      type: 'short-input',
      placeholder: 'Numeric lap number',
      condition: { field: 'operation', value: LAP_NUMBER_OPS },
      required: { field: 'operation', value: LAP_NUMBER_OPS },
    },
    {
      id: 'leagueId',
      title: 'League ID',
      type: 'short-input',
      placeholder: 'Numeric league ID',
      condition: { field: 'operation', value: LEAGUE_ID_OPS },
      required: { field: 'operation', value: LEAGUE_ID_OPS },
    },
    {
      id: 'marketId',
      title: 'Market ID',
      type: 'short-input',
      placeholder: 'Numeric market ID',
      condition: { field: 'operation', value: MARKET_ID_OPS },
      required: { field: 'operation', value: MARKET_ID_OPS },
    },
    {
      id: 'playerId',
      title: 'Player ID',
      type: 'short-input',
      placeholder: 'Numeric player ID',
      condition: { field: 'operation', value: PLAYER_ID_OPS },
      required: { field: 'operation', value: PLAYER_ID_OPS },
    },
    {
      id: 'query',
      title: 'Search Query',
      type: 'short-input',
      placeholder: 'Name to search for',
      condition: { field: 'operation', value: QUERY_OPS },
      required: { field: 'operation', value: QUERY_OPS },
    },
    {
      id: 'refereeId',
      title: 'Referee ID',
      type: 'short-input',
      placeholder: 'Numeric referee ID',
      condition: { field: 'operation', value: REFEREE_ID_OPS },
      required: { field: 'operation', value: REFEREE_ID_OPS },
    },
    {
      id: 'regionId',
      title: 'Region ID',
      type: 'short-input',
      placeholder: 'Numeric region ID',
      condition: { field: 'operation', value: REGION_ID_OPS },
      required: { field: 'operation', value: REGION_ID_OPS },
    },
    {
      id: 'roundId',
      title: 'Round ID',
      type: 'short-input',
      placeholder: 'Numeric round ID',
      condition: { field: 'operation', value: ROUND_ID_OPS },
      required: { field: 'operation', value: ROUND_ID_OPS },
    },
    {
      id: 'rumourId',
      title: 'Rumour ID',
      type: 'short-input',
      placeholder: 'Numeric transfer rumour ID',
      condition: { field: 'operation', value: RUMOUR_ID_OPS },
      required: { field: 'operation', value: RUMOUR_ID_OPS },
    },
    {
      id: 'seasonId',
      title: 'Season ID',
      type: 'short-input',
      placeholder: 'Numeric season ID',
      condition: { field: 'operation', value: SEASON_ID_OPS },
      required: { field: 'operation', value: SEASON_ID_OPS },
    },
    {
      id: 'stageId',
      title: 'Stage ID',
      type: 'short-input',
      placeholder: 'Numeric stage ID',
      condition: { field: 'operation', value: STAGE_ID_OPS },
      required: { field: 'operation', value: STAGE_ID_OPS },
    },
    {
      id: 'startDate',
      title: 'Start Date',
      type: 'short-input',
      placeholder: 'YYYY-MM-DD',
      wandConfig: DATE_WAND_CONFIG,
      condition: { field: 'operation', value: START_DATE_OPS },
      required: { field: 'operation', value: START_DATE_OPS },
    },
    {
      id: 'stateId',
      title: 'State ID',
      type: 'short-input',
      placeholder: 'Numeric state ID',
      condition: { field: 'operation', value: STATE_ID_OPS },
      required: { field: 'operation', value: STATE_ID_OPS },
    },
    {
      id: 'stintNumber',
      title: 'Stint Number',
      type: 'short-input',
      placeholder: 'Numeric stint number',
      condition: { field: 'operation', value: STINT_NUMBER_OPS },
      required: { field: 'operation', value: STINT_NUMBER_OPS },
    },
    {
      id: 'team1',
      title: 'Team 1 ID',
      type: 'short-input',
      placeholder: 'First team ID',
      condition: { field: 'operation', value: TEAM_1_OPS },
      required: { field: 'operation', value: TEAM_1_OPS },
    },
    {
      id: 'team2',
      title: 'Team 2 ID',
      type: 'short-input',
      placeholder: 'Second team ID',
      condition: { field: 'operation', value: TEAM_2_OPS },
      required: { field: 'operation', value: TEAM_2_OPS },
    },
    {
      id: 'teamId',
      title: 'Team ID',
      type: 'short-input',
      placeholder: 'Numeric team ID',
      condition: { field: 'operation', value: TEAM_ID_OPS },
      required: { field: 'operation', value: TEAM_ID_OPS },
    },
    {
      id: 'toTimestamp',
      title: 'To (UNIX timestamp)',
      type: 'short-input',
      placeholder: 'End UNIX timestamp',
      condition: { field: 'operation', value: TO_TIMESTAMP_OPS },
      required: { field: 'operation', value: TO_TIMESTAMP_OPS },
    },
    {
      id: 'transferId',
      title: 'Transfer ID',
      type: 'short-input',
      placeholder: 'Numeric transfer ID',
      condition: { field: 'operation', value: TRANSFER_ID_OPS },
      required: { field: 'operation', value: TRANSFER_ID_OPS },
    },
    {
      id: 'tvStationId',
      title: 'TV Station ID',
      type: 'short-input',
      placeholder: 'Numeric TV station ID',
      condition: { field: 'operation', value: TV_STATION_ID_OPS },
      required: { field: 'operation', value: TV_STATION_ID_OPS },
    },
    {
      id: 'typeId',
      title: 'Type ID',
      type: 'short-input',
      placeholder: 'Numeric type ID',
      condition: { field: 'operation', value: TYPE_ID_OPS },
      required: { field: 'operation', value: TYPE_ID_OPS },
    },
    {
      id: 'venueId',
      title: 'Venue ID',
      type: 'short-input',
      placeholder: 'Numeric venue ID',
      condition: { field: 'operation', value: VENUE_ID_OPS },
      required: { field: 'operation', value: VENUE_ID_OPS },
    },
    {
      id: 'include',
      title: 'Includes',
      type: 'short-input',
      placeholder: 'Semicolon-separated relations (e.g. participants;scores)',
      mode: 'advanced',
      condition: { field: 'operation', value: INCLUDE_OPS },
    },
    {
      id: 'filters',
      title: 'Filters',
      type: 'short-input',
      placeholder: 'Filters to apply (e.g. fixtureLeagues:501)',
      mode: 'advanced',
      condition: { field: 'operation', value: FILTER_OPS },
    },
    {
      id: 'per_page',
      title: 'Per Page',
      type: 'short-input',
      placeholder: 'Results per page (max 50)',
      mode: 'advanced',
      condition: { field: 'operation', value: PAGINATED_OPS },
    },
    {
      id: 'page',
      title: 'Page',
      type: 'short-input',
      placeholder: 'Page number',
      mode: 'advanced',
      condition: { field: 'operation', value: PAGINATED_OPS },
    },
    {
      id: 'order',
      title: 'Order',
      type: 'dropdown',
      options: [
        { label: 'Ascending', id: 'asc' },
        { label: 'Descending', id: 'desc' },
      ],
      mode: 'advanced',
      condition: { field: 'operation', value: PAGINATED_OPS },
    },
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      placeholder: 'Enter your Sportmonks API token',
      password: true,
      required: true,
    },
  ],
  tools: {
    access: [
      'sportmonks_football_expected_by_player',
      'sportmonks_football_expected_by_team',
      'sportmonks_football_get_all_commentaries',
      'sportmonks_football_get_all_fixtures',
      'sportmonks_football_get_all_players',
      'sportmonks_football_get_all_rivals',
      'sportmonks_football_get_all_teams',
      'sportmonks_football_get_all_transfer_rumours',
      'sportmonks_football_get_all_transfers',
      'sportmonks_football_get_brackets_by_season',
      'sportmonks_football_get_coach',
      'sportmonks_football_get_coaches',
      'sportmonks_football_get_coaches_by_country',
      'sportmonks_football_get_commentaries_by_fixture',
      'sportmonks_football_get_current_leagues_by_team',
      'sportmonks_football_get_expected_lineups_by_player',
      'sportmonks_football_get_expected_lineups_by_team',
      'sportmonks_football_get_extended_team_squad',
      'sportmonks_football_get_fixture',
      'sportmonks_football_get_fixtures_by_date',
      'sportmonks_football_get_fixtures_by_date_range',
      'sportmonks_football_get_fixtures_by_date_range_for_team',
      'sportmonks_football_get_fixtures_by_ids',
      'sportmonks_football_get_grouped_standings_by_round',
      'sportmonks_football_get_head_to_head',
      'sportmonks_football_get_inplay_livescores',
      'sportmonks_football_get_latest_coaches',
      'sportmonks_football_get_latest_fixtures',
      'sportmonks_football_get_latest_livescores',
      'sportmonks_football_get_latest_players',
      'sportmonks_football_get_latest_totw',
      'sportmonks_football_get_latest_transfers',
      'sportmonks_football_get_league',
      'sportmonks_football_get_leagues',
      'sportmonks_football_get_leagues_by_country',
      'sportmonks_football_get_leagues_by_date',
      'sportmonks_football_get_leagues_by_team',
      'sportmonks_football_get_live_leagues',
      'sportmonks_football_get_live_probabilities',
      'sportmonks_football_get_live_probabilities_by_fixture',
      'sportmonks_football_get_live_standings_by_league',
      'sportmonks_football_get_livescores',
      'sportmonks_football_get_match_facts',
      'sportmonks_football_get_match_facts_by_date_range',
      'sportmonks_football_get_match_facts_by_fixture',
      'sportmonks_football_get_match_facts_by_league',
      'sportmonks_football_get_past_fixtures_by_tv_station',
      'sportmonks_football_get_player',
      'sportmonks_football_get_players_by_country',
      'sportmonks_football_get_postmatch_news',
      'sportmonks_football_get_postmatch_news_by_season',
      'sportmonks_football_get_predictability_by_league',
      'sportmonks_football_get_prematch_news',
      'sportmonks_football_get_prematch_news_by_season',
      'sportmonks_football_get_prematch_news_upcoming',
      'sportmonks_football_get_probabilities',
      'sportmonks_football_get_probabilities_by_fixture',
      'sportmonks_football_get_referee',
      'sportmonks_football_get_referees',
      'sportmonks_football_get_referees_by_country',
      'sportmonks_football_get_referees_by_season',
      'sportmonks_football_get_rivals_by_team',
      'sportmonks_football_get_round',
      'sportmonks_football_get_round_statistics',
      'sportmonks_football_get_rounds',
      'sportmonks_football_get_rounds_by_season',
      'sportmonks_football_get_schedules_by_season',
      'sportmonks_football_get_schedules_by_season_and_team',
      'sportmonks_football_get_schedules_by_team',
      'sportmonks_football_get_season',
      'sportmonks_football_get_seasons',
      'sportmonks_football_get_seasons_by_team',
      'sportmonks_football_get_stage',
      'sportmonks_football_get_stage_statistics',
      'sportmonks_football_get_stages',
      'sportmonks_football_get_stages_by_season',
      'sportmonks_football_get_standing_corrections_by_season',
      'sportmonks_football_get_standings',
      'sportmonks_football_get_standings_by_round',
      'sportmonks_football_get_standings_by_season',
      'sportmonks_football_get_state',
      'sportmonks_football_get_states',
      'sportmonks_football_get_team',
      'sportmonks_football_get_team_rankings',
      'sportmonks_football_get_team_rankings_by_date',
      'sportmonks_football_get_team_rankings_by_team',
      'sportmonks_football_get_team_squad',
      'sportmonks_football_get_team_squad_by_season',
      'sportmonks_football_get_teams_by_country',
      'sportmonks_football_get_teams_by_season',
      'sportmonks_football_get_topscorers_by_season',
      'sportmonks_football_get_topscorers_by_stage',
      'sportmonks_football_get_totw',
      'sportmonks_football_get_totw_by_round',
      'sportmonks_football_get_transfer',
      'sportmonks_football_get_transfer_rumour',
      'sportmonks_football_get_transfer_rumours_between_dates',
      'sportmonks_football_get_transfer_rumours_by_player',
      'sportmonks_football_get_transfer_rumours_by_team',
      'sportmonks_football_get_transfers_between_dates',
      'sportmonks_football_get_transfers_by_player',
      'sportmonks_football_get_transfers_by_team',
      'sportmonks_football_get_tv_station',
      'sportmonks_football_get_tv_stations',
      'sportmonks_football_get_tv_stations_by_fixture',
      'sportmonks_football_get_upcoming_fixtures_by_market',
      'sportmonks_football_get_upcoming_fixtures_by_tv_station',
      'sportmonks_football_get_value_bets',
      'sportmonks_football_get_value_bets_by_fixture',
      'sportmonks_football_get_venue',
      'sportmonks_football_get_venues',
      'sportmonks_football_get_venues_by_season',
      'sportmonks_football_search_coaches',
      'sportmonks_football_search_fixtures',
      'sportmonks_football_search_leagues',
      'sportmonks_football_search_players',
      'sportmonks_football_search_referees',
      'sportmonks_football_search_rounds',
      'sportmonks_football_search_seasons',
      'sportmonks_football_search_stages',
      'sportmonks_football_search_teams',
      'sportmonks_football_search_venues',
      'sportmonks_motorsport_get_all_fixtures',
      'sportmonks_motorsport_get_current_leagues_by_team',
      'sportmonks_motorsport_get_driver',
      'sportmonks_motorsport_get_driver_standings',
      'sportmonks_motorsport_get_driver_standings_by_season',
      'sportmonks_motorsport_get_drivers',
      'sportmonks_motorsport_get_drivers_by_country',
      'sportmonks_motorsport_get_drivers_by_season',
      'sportmonks_motorsport_get_fixture',
      'sportmonks_motorsport_get_fixtures_by_date',
      'sportmonks_motorsport_get_fixtures_by_date_range',
      'sportmonks_motorsport_get_fixtures_by_ids',
      'sportmonks_motorsport_get_laps_by_fixture',
      'sportmonks_motorsport_get_laps_by_fixture_and_driver',
      'sportmonks_motorsport_get_laps_by_fixture_and_lap',
      'sportmonks_motorsport_get_latest_laps_by_fixture',
      'sportmonks_motorsport_get_latest_pitstops_by_fixture',
      'sportmonks_motorsport_get_latest_stints_by_fixture',
      'sportmonks_motorsport_get_latest_updated_drivers',
      'sportmonks_motorsport_get_latest_updated_fixtures',
      'sportmonks_motorsport_get_league',
      'sportmonks_motorsport_get_leagues',
      'sportmonks_motorsport_get_leagues_by_country',
      'sportmonks_motorsport_get_leagues_by_date',
      'sportmonks_motorsport_get_leagues_by_live',
      'sportmonks_motorsport_get_leagues_by_team',
      'sportmonks_motorsport_get_livescores',
      'sportmonks_motorsport_get_pitstops_by_fixture',
      'sportmonks_motorsport_get_pitstops_by_fixture_and_driver',
      'sportmonks_motorsport_get_pitstops_by_fixture_and_lap',
      'sportmonks_motorsport_get_race_results_by_season_and_driver',
      'sportmonks_motorsport_get_race_results_by_season_and_team',
      'sportmonks_motorsport_get_schedules_by_season',
      'sportmonks_motorsport_get_season',
      'sportmonks_motorsport_get_seasons',
      'sportmonks_motorsport_get_stage',
      'sportmonks_motorsport_get_stages',
      'sportmonks_motorsport_get_stages_by_season',
      'sportmonks_motorsport_get_state',
      'sportmonks_motorsport_get_states',
      'sportmonks_motorsport_get_stints_by_fixture',
      'sportmonks_motorsport_get_stints_by_fixture_and_driver',
      'sportmonks_motorsport_get_stints_by_fixture_and_stint',
      'sportmonks_motorsport_get_team',
      'sportmonks_motorsport_get_team_standings',
      'sportmonks_motorsport_get_team_standings_by_season',
      'sportmonks_motorsport_get_teams',
      'sportmonks_motorsport_get_teams_by_country',
      'sportmonks_motorsport_get_teams_by_season',
      'sportmonks_motorsport_get_venue',
      'sportmonks_motorsport_get_venues',
      'sportmonks_motorsport_get_venues_by_season',
      'sportmonks_motorsport_search_drivers',
      'sportmonks_motorsport_search_leagues',
      'sportmonks_motorsport_search_stages',
      'sportmonks_motorsport_search_teams',
      'sportmonks_motorsport_search_venues',
      'sportmonks_odds_get_all_historical_odds',
      'sportmonks_odds_get_all_inplay_odds',
      'sportmonks_odds_get_all_pre_match_odds',
      'sportmonks_odds_get_all_premium_odds',
      'sportmonks_odds_get_bookmaker',
      'sportmonks_odds_get_bookmaker_event_ids_by_fixture',
      'sportmonks_odds_get_bookmakers',
      'sportmonks_odds_get_bookmakers_by_fixture',
      'sportmonks_odds_get_inplay_odds_by_fixture',
      'sportmonks_odds_get_inplay_odds_by_fixture_and_bookmaker',
      'sportmonks_odds_get_inplay_odds_by_fixture_and_market',
      'sportmonks_odds_get_last_updated_inplay_odds',
      'sportmonks_odds_get_last_updated_pre_match_odds',
      'sportmonks_odds_get_market',
      'sportmonks_odds_get_markets',
      'sportmonks_odds_get_pre_match_odds_by_fixture',
      'sportmonks_odds_get_pre_match_odds_by_fixture_and_bookmaker',
      'sportmonks_odds_get_pre_match_odds_by_fixture_and_market',
      'sportmonks_odds_get_premium_odds_by_fixture',
      'sportmonks_odds_get_premium_odds_by_fixture_and_bookmaker',
      'sportmonks_odds_get_premium_odds_by_fixture_and_market',
      'sportmonks_odds_get_updated_historical_odds_between',
      'sportmonks_odds_get_updated_premium_odds_between',
      'sportmonks_odds_search_bookmakers',
      'sportmonks_odds_search_markets',
      'sportmonks_core_get_cities',
      'sportmonks_core_get_city',
      'sportmonks_core_get_continent',
      'sportmonks_core_get_continents',
      'sportmonks_core_get_countries',
      'sportmonks_core_get_country',
      'sportmonks_core_get_entity_filters',
      'sportmonks_core_get_my_usage',
      'sportmonks_core_get_region',
      'sportmonks_core_get_regions',
      'sportmonks_core_get_timezones',
      'sportmonks_core_get_type',
      'sportmonks_core_get_type_by_entity',
      'sportmonks_core_get_types',
      'sportmonks_core_search_cities',
      'sportmonks_core_search_countries',
      'sportmonks_core_search_regions',
    ],
    config: {
      tool: (params) => `sportmonks_${params.operation}`,
      params: (params) => {
        const cleaned: Record<string, any> = {}
        Object.entries(params).forEach(([key, value]) => {
          if (key === 'operation') return
          if (value !== undefined && value !== null && value !== '') {
            cleaned[key] = value
          }
        })
        return cleaned
      },
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    apiKey: { type: 'string', description: 'Sportmonks API token' },
    bookmakerId: { type: 'string', description: 'Bookmaker ID' },
    cityId: { type: 'string', description: 'City ID' },
    coachId: { type: 'string', description: 'Coach ID' },
    continentId: { type: 'string', description: 'Continent ID' },
    countryId: { type: 'string', description: 'Country ID' },
    date: { type: 'string', description: 'Date' },
    driverId: { type: 'string', description: 'Driver ID' },
    endDate: { type: 'string', description: 'End Date' },
    fixtureId: { type: 'string', description: 'Fixture ID' },
    fixtureIds: { type: 'string', description: 'Fixture IDs' },
    fromTimestamp: { type: 'string', description: 'From (UNIX timestamp)' },
    ids: { type: 'string', description: 'IDs' },
    lapNumber: { type: 'string', description: 'Lap Number' },
    leagueId: { type: 'string', description: 'League ID' },
    marketId: { type: 'string', description: 'Market ID' },
    playerId: { type: 'string', description: 'Player ID' },
    query: { type: 'string', description: 'Search Query' },
    refereeId: { type: 'string', description: 'Referee ID' },
    regionId: { type: 'string', description: 'Region ID' },
    roundId: { type: 'string', description: 'Round ID' },
    rumourId: { type: 'string', description: 'Rumour ID' },
    seasonId: { type: 'string', description: 'Season ID' },
    stageId: { type: 'string', description: 'Stage ID' },
    startDate: { type: 'string', description: 'Start Date' },
    stateId: { type: 'string', description: 'State ID' },
    stintNumber: { type: 'string', description: 'Stint Number' },
    team1: { type: 'string', description: 'Team 1 ID' },
    team2: { type: 'string', description: 'Team 2 ID' },
    teamId: { type: 'string', description: 'Team ID' },
    toTimestamp: { type: 'string', description: 'To (UNIX timestamp)' },
    transferId: { type: 'string', description: 'Transfer ID' },
    tvStationId: { type: 'string', description: 'TV Station ID' },
    typeId: { type: 'string', description: 'Type ID' },
    venueId: { type: 'string', description: 'Venue ID' },
    include: { type: 'string', description: 'Semicolon-separated relations to include' },
    filters: { type: 'string', description: 'Filters to apply' },
    per_page: { type: 'string', description: 'Results per page (max 50)' },
    page: { type: 'string', description: 'Page number' },
    order: { type: 'string', description: 'Order direction (asc or desc)' },
  },
  outputs: {
    bookmaker: { type: 'json', description: 'Single bookmaker object' },
    bookmakerEvents: { type: 'json', description: 'Array of bookmakerEvents' },
    bookmakers: { type: 'json', description: 'Array of bookmakers' },
    brackets: { type: 'json', description: 'brackets (JSON)' },
    cities: { type: 'json', description: 'Array of cities' },
    city: { type: 'json', description: 'Single city object' },
    coach: { type: 'json', description: 'Single coach object' },
    coaches: { type: 'json', description: 'Array of coaches' },
    commentaries: { type: 'json', description: 'Array of commentaries' },
    continent: { type: 'json', description: 'Single continent object' },
    continents: { type: 'json', description: 'Array of continents' },
    corrections: { type: 'json', description: 'Array of corrections' },
    countries: { type: 'json', description: 'Array of countries' },
    country: { type: 'json', description: 'Single country object' },
    driver: { type: 'json', description: 'Single driver object' },
    drivers: { type: 'json', description: 'Array of drivers' },
    entityFilters: { type: 'json', description: 'entityFilters (JSON)' },
    expected: { type: 'json', description: 'Array of expected' },
    expectedLineups: { type: 'json', description: 'Array of expectedLineups' },
    fixture: { type: 'json', description: 'Single fixture object' },
    fixtures: { type: 'json', description: 'Array of fixtures' },
    historicalOdds: { type: 'json', description: 'Array of historicalOdds' },
    laps: { type: 'json', description: 'Array of laps' },
    league: { type: 'json', description: 'Single league object' },
    leagues: { type: 'json', description: 'Array of leagues' },
    market: { type: 'json', description: 'Single market object' },
    markets: { type: 'json', description: 'Array of markets' },
    matchFacts: { type: 'json', description: 'Array of matchFacts' },
    news: { type: 'json', description: 'Array of news' },
    odds: { type: 'json', description: 'Array of odds' },
    pitstops: { type: 'json', description: 'Array of pitstops' },
    player: { type: 'json', description: 'Single player object' },
    players: { type: 'json', description: 'Array of players' },
    predictability: { type: 'json', description: 'Array of predictability' },
    predictions: { type: 'json', description: 'Array of predictions' },
    premiumOdds: { type: 'json', description: 'Array of premiumOdds' },
    referee: { type: 'json', description: 'Single referee object' },
    referees: { type: 'json', description: 'Array of referees' },
    region: { type: 'json', description: 'Single region object' },
    regions: { type: 'json', description: 'Array of regions' },
    results: { type: 'json', description: 'Array of results' },
    rivals: { type: 'json', description: 'Array of rivals' },
    round: { type: 'json', description: 'Single round object' },
    rounds: { type: 'json', description: 'Array of rounds' },
    schedules: { type: 'json', description: 'Array of schedules' },
    season: { type: 'json', description: 'Single season object' },
    seasons: { type: 'json', description: 'Array of seasons' },
    squad: { type: 'json', description: 'Array of squad' },
    stage: { type: 'json', description: 'Single stage object' },
    stages: { type: 'json', description: 'Array of stages' },
    standings: { type: 'json', description: 'Array of standings' },
    state: { type: 'json', description: 'Single state object' },
    states: { type: 'json', description: 'Array of states' },
    statistics: { type: 'json', description: 'Array of statistics' },
    stints: { type: 'json', description: 'Array of stints' },
    team: { type: 'json', description: 'Single team object' },
    teamRankings: { type: 'json', description: 'Array of teamRankings' },
    teams: { type: 'json', description: 'Array of teams' },
    timezones: { type: 'json', description: 'Array of timezones' },
    topscorers: { type: 'json', description: 'Array of topscorers' },
    totw: { type: 'json', description: 'Array of totw' },
    transfer: { type: 'json', description: 'Single transfer object' },
    transferRumour: { type: 'json', description: 'Single transferRumour object' },
    transferRumours: { type: 'json', description: 'Array of transferRumours' },
    transfers: { type: 'json', description: 'Array of transfers' },
    tvStation: { type: 'json', description: 'Single tvStation object' },
    tvStations: { type: 'json', description: 'Array of tvStations' },
    type: { type: 'json', description: 'Single type object' },
    types: { type: 'json', description: 'Array of types' },
    typesByEntity: { type: 'json', description: 'typesByEntity (JSON)' },
    usage: { type: 'json', description: 'Array of usage' },
    valueBets: { type: 'json', description: 'Array of valueBets' },
    venue: { type: 'json', description: 'Single venue object' },
    venues: { type: 'json', description: 'Array of venues' },
    pagination: {
      type: 'json',
      description: 'Pagination metadata {count, per_page, current_page, next_page, has_more}',
    },
  },
}

export const SportmonksBlockMeta = {
  tags: ['data-analytics'],
  url: 'https://www.sportmonks.com',
  templates: [
    {
      icon: SportmonksIcon,
      title: 'Daily football fixtures digest',
      prompt:
        "Build a scheduled daily workflow that fetches today's football fixtures from Sportmonks for the leagues I follow, summarizes the key matchups and kickoff times, and posts the digest to Slack.",
      modules: ['scheduled', 'agent', 'workflows'],
      category: 'productivity',
      tags: ['automation', 'reporting'],
      alsoIntegrations: ['slack'],
    },
    {
      icon: SportmonksIcon,
      title: 'Live football score alerter',
      prompt:
        'Create a scheduled workflow that polls Sportmonks inplay football scores, detects goals and status changes since the last run, and pings Slack with the updated scoreline for tracked matches.',
      modules: ['scheduled', 'tables', 'agent', 'workflows'],
      category: 'operations',
      tags: ['monitoring', 'automation'],
      alsoIntegrations: ['slack'],
    },
    {
      icon: SportmonksIcon,
      title: 'Weekly league standings report',
      prompt:
        'Build a scheduled weekly workflow that pulls the Sportmonks football standings and topscorers for a season, formats a league table with recent form, and emails the report to the group.',
      modules: ['scheduled', 'agent', 'workflows'],
      category: 'operations',
      tags: ['reporting', 'analysis'],
      alsoIntegrations: ['gmail'],
    },
    {
      icon: SportmonksIcon,
      title: 'Race weekend schedule digest',
      prompt:
        "Build a scheduled workflow that fetches this weekend's motorsport sessions from Sportmonks, summarizes the practice, qualifying, and race times, and posts the schedule to Slack.",
      modules: ['scheduled', 'agent', 'workflows'],
      category: 'productivity',
      tags: ['automation', 'reporting'],
      alsoIntegrations: ['slack'],
    },
    {
      icon: SportmonksIcon,
      title: 'Motorsport championship tracker',
      prompt:
        'Create a scheduled weekly workflow that pulls the Sportmonks motorsport driver and constructor standings for the current season, formats the championship tables, and emails them to the group.',
      modules: ['scheduled', 'agent', 'workflows'],
      category: 'operations',
      tags: ['reporting', 'analysis'],
      alsoIntegrations: ['gmail'],
    },
    {
      icon: SportmonksIcon,
      title: 'Pre-match odds snapshot',
      prompt:
        'Build a workflow that pulls Sportmonks pre-match odds for a fixture across selected bookmakers, computes the implied probability for each outcome, and writes the snapshot to a table.',
      modules: ['tables', 'agent', 'workflows'],
      category: 'operations',
      tags: ['finance', 'analysis'],
    },
    {
      icon: SportmonksIcon,
      title: 'Live odds movement alerter',
      prompt:
        'Create a scheduled workflow that polls Sportmonks in-play odds for a fixture, detects sharp price moves since the last run, and pings Slack with the updated lines.',
      modules: ['scheduled', 'tables', 'agent', 'workflows'],
      category: 'operations',
      tags: ['monitoring', 'finance'],
      alsoIntegrations: ['slack'],
    },
    {
      icon: SportmonksIcon,
      title: 'Head-to-head match preview',
      prompt:
        'Create a workflow that takes two team names, resolves them to IDs via Sportmonks football team search, pulls their head-to-head history and current standings, and writes a match preview file.',
      modules: ['agent', 'files', 'workflows'],
      category: 'productivity',
      tags: ['research', 'content'],
    },
  ],
  skills: [
    {
      name: 'daily-football-fixtures',
      description: "List a day's football fixtures from Sportmonks, optionally filtered by league.",
      content:
        '# Daily Football Fixtures\n\nGet the football matches scheduled for a given day.\n\n## Steps\n1. Use Get Football Fixtures by Date with the target date in YYYY-MM-DD format.\n2. Optionally set Includes to `participants;scores;league` to enrich each fixture.\n3. Optionally set Filters such as `fixtureLeagues:501,271` to restrict to specific leagues.\n\n## Output\nA list of fixtures with kickoff time, the participating teams, and league.',
    },
    {
      name: 'live-football-scores',
      description: 'Fetch in-play football matches and their current scores from Sportmonks.',
      content:
        '# Live Football Scores\n\nSee which matches are being played now and the live score.\n\n## Steps\n1. Use Get Inplay Football Scores to fetch matches in progress.\n2. Set Includes to `participants;scores` for team names and the scoreline.\n3. Optionally filter with `fixtureLeagues:501`.\n\n## Output\nA list of live fixtures, each with the two teams, current score, and match state.',
    },
    {
      name: 'football-league-table',
      description: 'Build a football league standings table for a season from Sportmonks.',
      content:
        "# Football League Table\n\nGet the current standings for a competition.\n\n## Steps\n1. Find the season ID (use Get Football Leagues, then its current season).\n2. Use Get Football Standings by Season with that season ID.\n3. Set Includes to `participant` for team names and `form` for recent results.\n\n## Output\nAn ordered league table with each team's position, points, and recent form.",
    },
    {
      name: 'race-weekend-sessions',
      description: 'List the motorsport sessions on a given date from Sportmonks.',
      content:
        '# Race Weekend Sessions\n\nGet the practice, qualifying, and race sessions for a day.\n\n## Steps\n1. Use Get Motorsport Fixtures by Date with the target date in YYYY-MM-DD format.\n2. Set Includes to `venue;participants` to attach the track and entrants.\n\n## Output\nA list of sessions for the day with type (Practice/Qualifying/Race), track, and start time.',
    },
    {
      name: 'motorsport-championship',
      description: 'Fetch driver and constructor championship standings for a motorsport season.',
      content:
        "# Motorsport Championship\n\nGet the title race state for a season.\n\n## Steps\n1. Use Get Motorsport Driver Standings by Season with the season ID.\n2. Use Get Motorsport Team Standings by Season with the same season ID.\n3. Set Includes to `participant` for driver/team names.\n\n## Output\nOrdered drivers and constructors tables with each participant's position and points.",
    },
    {
      name: 'pre-match-odds',
      description: 'Fetch pre-match odds for a fixture and compute implied probabilities.',
      content:
        '# Pre-match Odds\n\nGet the betting odds for an upcoming fixture.\n\n## Steps\n1. Use Get Pre-match Odds by Fixture with the fixture ID.\n2. Set Includes to `market;bookmaker` and optionally Filters like `bookmakers:2,14` to narrow results.\n\n## Output\nThe odds per outcome with decimal value and implied probability, grouped by market and bookmaker.',
    },
    {
      name: 'odds-line-shopping',
      description: 'Find the best available price per outcome across bookmakers.',
      content:
        '# Odds Line Shopping\n\nFind the best odds for each outcome.\n\n## Steps\n1. Use Get Pre-match Odds by Fixture for the fixture (do not filter to one bookmaker).\n2. Group the returned odds by market and outcome label.\n3. For each outcome, pick the highest value and note its bookmaker_id.\n\n## Output\nFor each outcome, the best decimal price and which bookmaker offers it.',
    },
    {
      name: 'resolve-country',
      description:
        'Resolve a country name to its Sportmonks ID and ISO codes via Core reference data.',
      content:
        '# Resolve Country\n\nNormalize a country name to Sportmonks reference data.\n\n## Steps\n1. Use Search Countries with the country name.\n2. Read the matching country id, iso2, iso3, and fifa_name.\n\n## Output\nThe country id plus its ISO2, ISO3, and FIFA codes for use in other lookups.',
    },
  ],
} as const satisfies BlockMeta
