import { chmod, mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'

const APP_NAME = 'Center'
const BUNDLE_NAME = `${APP_NAME}.app`
const DEFAULT_WORKSPACE_ID = 'local-test'
const DEFAULT_PORT = '6888'

async function main() {
  const repoRoot = path.resolve(import.meta.dir, '..')
  const outputRoot = path.resolve(
    process.env.CENTER_APP_OUTPUT_DIR ?? path.join(repoRoot, 'var/center/apps')
  )
  assertProjectLocal(repoRoot, outputRoot)

  const appPath = path.join(outputRoot, BUNDLE_NAME)
  const contentsPath = path.join(appPath, 'Contents')
  const macOSPath = path.join(contentsPath, 'MacOS')
  const resourcesPath = path.join(contentsPath, 'Resources')
  const executablePath = path.join(macOSPath, APP_NAME)

  await rm(appPath, { recursive: true, force: true })
  await mkdir(macOSPath, { recursive: true })
  await mkdir(resourcesPath, { recursive: true })
  await writeFile(path.join(contentsPath, 'Info.plist'), createInfoPlist(), 'utf8')
  await writeFile(executablePath, createLauncher(repoRoot), 'utf8')
  await chmod(executablePath, 0o755)
  await writeFile(path.join(resourcesPath, 'README.md'), createReadme(repoRoot), 'utf8')

  console.log(JSON.stringify({ appPath, executablePath }, null, 2))
}

function createInfoPlist(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>${APP_NAME}</string>
  <key>CFBundleIdentifier</key>
  <string>local.sim.center</string>
  <key>CFBundleName</key>
  <string>${APP_NAME}</string>
  <key>CFBundleDisplayName</key>
  <string>${APP_NAME}</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>0.1.0</string>
  <key>CFBundleVersion</key>
  <string>1</string>
  <key>LSMinimumSystemVersion</key>
  <string>13.0</string>
  <key>NSHighResolutionCapable</key>
  <true/>
</dict>
</plist>
`
}

function createLauncher(repoRoot: string): string {
  return `#!/bin/zsh
set -euo pipefail

REPO_ROOT=${shellQuote(repoRoot)}
PORT="\${CENTER_PORT:-${DEFAULT_PORT}}"
WORKSPACE_ID="\${CENTER_WORKSPACE_ID:-${DEFAULT_WORKSPACE_ID}}"
URL="http://localhost:\${PORT}/workspace/\${WORKSPACE_ID}/center"
LOG_DIR="\${HOME}/Library/Logs"
LOG_FILE="\${LOG_DIR}/Center.app.log"
WAIT_SECONDS="\${CENTER_APP_WAIT_SECONDS:-60}"

mkdir -p "\${LOG_DIR}"

if ! command -v bun >/dev/null 2>&1; then
  osascript -e 'display dialog "Center.app requires bun on PATH." buttons {"OK"} default button "OK"' >/dev/null 2>&1 || true
  exit 127
fi

if curl -fsS "\${URL}" >/dev/null 2>&1; then
  if [[ "\${CENTER_APP_OPEN:-1}" != "0" ]]; then
    open "\${URL}"
  fi
  exit 0
fi

(
  cd "\${REPO_ROOT}/apps/sim"
  CENTER_DEV=1 NEXT_TELEMETRY_DISABLED=1 NODE_OPTIONS="\${NODE_OPTIONS:---max-old-space-size=4096}" bun run dev:center >>"\${LOG_FILE}" 2>&1
) &

attempt=0
while (( attempt < WAIT_SECONDS )); do
  if curl -fsS "\${URL}" >/dev/null 2>&1; then
    if [[ "\${CENTER_APP_OPEN:-1}" != "0" ]]; then
      open "\${URL}"
    fi
    exit 0
  fi
  attempt=$((attempt + 1))
  sleep 1
done

osascript -e 'display dialog "Center.app could not start Center. See ~/Library/Logs/Center.app.log." buttons {"OK"} default button "OK"' >/dev/null 2>&1 || true
exit 1
`
}

function createReadme(repoRoot: string): string {
  return `# Center.app

Generated by:

\`\`\`text
bun run package:center-app
\`\`\`

Launch target:

\`\`\`text
${repoRoot}/apps/sim
\`\`\`

Runtime:

\`\`\`text
CENTER_DEV=1 NEXT_TELEMETRY_DISABLED=1 bun run dev:center
http://localhost:${DEFAULT_PORT}/workspace/${DEFAULT_WORKSPACE_ID}/center
\`\`\`

Profile data remains in the browser-local Center spine unless a later approved phase changes storage.
`
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`
}

function assertProjectLocal(repoRoot: string, target: string) {
  const relative = path.relative(repoRoot, target)
  if (relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new Error(`Refusing to write Center.app outside the repo: ${target}`)
  }
}

await main()
