export type { AddResourceDropdownProps, AvailableItem } from './add-resource-dropdown'
export { AddResourceDropdown, useAvailableResources } from './add-resource-dropdown'
export { ResourceActions, ResourceContent } from './resource-content'
export type { ResourceTypeConfig } from './resource-registry'
export { getResourceConfig, RESOURCE_REGISTRY, RESOURCE_TYPES } from './resource-registry'
export { invalidateResourceQueries } from './resource-registry/resource-query-invalidation'
export { ResourceTabs } from './resource-tabs'
